#!/bin/bash

VERSION=$1

if [ "$VERSION" = "" ]; then
    echo
    echo "Defina a versão para gerar um build. Exemplo:"
    echo "./makebuild 2.10.0"
    exit 1
fi

FILE_VERSION=`echo $VERSION | tr . -`

mkdir -p build/
sudo rm -R build/* 2> /dev/null
git checkout-index --prefix=build/ -a -f
cd build
composer install --no-dev --ignore-platform-reqs --optimize-autoloader
git clone git@github.com:portabilis/i-educar-reports-package.git ieducar/modules/Reports
sudo rm -R ieducar/modules/Reports/.git
tar -zcvf i-educar-${FILE_VERSION}.tar.gz *
