INSERT INTO cadastro.orgao_emissor_rg VALUES (8, 'CRA', 'Conselho Regional de Administração', 'I', 61);
INSERT INTO cadastro.orgao_emissor_rg VALUES (10, 'CRB', 'Conselho Regional de Biblioteconomia', 'I', 63);
INSERT INTO cadastro.orgao_emissor_rg VALUES (11, 'CRC', 'Conselho Regional de Contabilidade', 'I', 64);
INSERT INTO cadastro.orgao_emissor_rg VALUES (12, 'CRECI', 'Conselho Regional de Corretores Imóveis', 'I', 65);
INSERT INTO cadastro.orgao_emissor_rg VALUES (14, 'CREA', 'Conselho Regional de Engenharia, Arquitetura e Agronomia', 'I', 67);
INSERT INTO cadastro.orgao_emissor_rg VALUES (18, 'CRM', 'Conselho Regional de Medicina', 'I', 71);
INSERT INTO cadastro.orgao_emissor_rg VALUES (20, 'OMB', 'Ordem dos Músicos do Brasil', 'I', 73);
INSERT INTO cadastro.orgao_emissor_rg VALUES (22, 'CRO', 'Conselho Regional de Odontologia', 'I', 75);
INSERT INTO cadastro.orgao_emissor_rg VALUES (24, 'CRP', 'Conselho Regional de Psicologia', 'I', 77);
INSERT INTO cadastro.orgao_emissor_rg VALUES (25, 'CRQ', 'Conselho Regional de Química', 'I', 78);
INSERT INTO cadastro.orgao_emissor_rg VALUES (27, 'OAB', 'Ordem dos Advogados do Brasil', 'I', 80);
INSERT INTO cadastro.orgao_emissor_rg VALUES (13, 'COREN', 'Conselho Regional de Enfermagem', 'I', 66);
INSERT INTO cadastro.orgao_emissor_rg VALUES (16, 'CRF', 'Conselho Regional de Farmácia', 'I', 69);
INSERT INTO cadastro.orgao_emissor_rg VALUES (21, 'CRN', 'Conselho Regional de Nutrição', 'I', 74);
INSERT INTO cadastro.orgao_emissor_rg VALUES (2, 'M MILITAR', 'Ministérios Militares', 'I', 40);
INSERT INTO cadastro.orgao_emissor_rg VALUES (3, 'MAE', 'Ministério da Aeronáutica', 'I', 41);
INSERT INTO cadastro.orgao_emissor_rg VALUES (4, 'MEX', 'Ministério do Exército', 'I', 42);
INSERT INTO cadastro.orgao_emissor_rg VALUES (5, 'MMA', 'Ministério da Marinha', 'I', 43);
INSERT INTO cadastro.orgao_emissor_rg VALUES (6, 'DPF', 'Polícia Federal', 'I', 44);
INSERT INTO cadastro.orgao_emissor_rg VALUES (7, 'I CLA', 'Carteira de Identidade Classista', 'I', 60);
INSERT INTO cadastro.orgao_emissor_rg VALUES (9, 'CRAS', 'Conselho Regional de Assist. Social', 'I', 62);
INSERT INTO cadastro.orgao_emissor_rg VALUES (15, 'CRE', 'Conselho Regional de Estatística', 'I', 68);
INSERT INTO cadastro.orgao_emissor_rg VALUES (17, 'CREFIT', 'Conselho Regional de Fisioterapia e Terapia Ocupacional', 'I', 70);
INSERT INTO cadastro.orgao_emissor_rg VALUES (19, 'CRV', 'Conselho Regional de Medicina Veterinária', 'I', 72);
INSERT INTO cadastro.orgao_emissor_rg VALUES (23, 'CRPRE', 'Conselho Regional de Profissionais de Relações Públicas', 'I', 76);
INSERT INTO cadastro.orgao_emissor_rg VALUES (26, 'CRRC', 'Conselho Regional de Representantes Comerciais', 'I', 79);
INSERT INTO cadastro.orgao_emissor_rg VALUES (28, 'OUTRO', 'Outros Emissores', 'I', 81);
INSERT INTO cadastro.orgao_emissor_rg VALUES (29, 'EST', 'Documento Estrangeiro', 'I', 82);
INSERT INTO cadastro.orgao_emissor_rg VALUES (31, 'DETRAN', 'Departamento Estadual de Trânsito', 'I', 83);
INSERT INTO cadastro.orgao_emissor_rg VALUES (1, 'SSP', 'Secretaria de Segurança Pública', 'I', 10);
