INSERT INTO cadastro.deficiencia VALUES (8, 'Deficiência Mental', NULL, false);
INSERT INTO cadastro.deficiencia VALUES (10, 'Autismo Clássico', NULL, false);
INSERT INTO cadastro.deficiencia VALUES (11, 'Síndrome de Asperger', NULL, false);
INSERT INTO cadastro.deficiencia VALUES (12, 'Síndrome de Rett', NULL, false);
INSERT INTO cadastro.deficiencia VALUES (13, 'Transtorno desintegrativo da infância (psicose infantil)', NULL, false);
INSERT INTO cadastro.deficiencia VALUES (14, 'Altas Habilidades/Superdotação', NULL, false);
INSERT INTO cadastro.deficiencia VALUES (2, 'Cegueira', 1, false);
INSERT INTO cadastro.deficiencia VALUES (3, 'Baixa Visão', 2, false);
INSERT INTO cadastro.deficiencia VALUES (4, 'Surdez', 3, false);
INSERT INTO cadastro.deficiencia VALUES (5, 'Deficiência Auditiva', 4, false);
INSERT INTO cadastro.deficiencia VALUES (6, 'Surdocegueira', 5, false);
INSERT INTO cadastro.deficiencia VALUES (7, 'Deficiência Física', 6, false);
INSERT INTO cadastro.deficiencia VALUES (9, 'Deficiência Múltipla', 8, false);
