INSERT INTO consistenciacao.campo_consistenciacao VALUES (1, 'CPF ou CNPJ', 'N', 14);
INSERT INTO consistenciacao.campo_consistenciacao VALUES (2, 'Nome pessoa física ou jurídica', 'N', 150);
INSERT INTO consistenciacao.campo_consistenciacao VALUES (3, 'E-mail', 'N', 50);
INSERT INTO consistenciacao.campo_consistenciacao VALUES (4, 'URL', 'N', 60);
INSERT INTO consistenciacao.campo_consistenciacao VALUES (5, 'Data nascimento', 'N', 20);
INSERT INTO consistenciacao.campo_consistenciacao VALUES (6, 'Número RG', 'N', 10);
INSERT INTO consistenciacao.campo_consistenciacao VALUES (7, 'Órgão expedidor RG', 'S', 20);
INSERT INTO consistenciacao.campo_consistenciacao VALUES (8, 'Data expedição RG', 'N', 20);
INSERT INTO consistenciacao.campo_consistenciacao VALUES (9, 'UF expedição RG', 'S', 30);
INSERT INTO consistenciacao.campo_consistenciacao VALUES (10, 'Tipo certidão civil', 'S', 2);
INSERT INTO consistenciacao.campo_consistenciacao VALUES (11, 'Número termo certidão civil', 'N', 8);
INSERT INTO consistenciacao.campo_consistenciacao VALUES (12, 'Número livro certidão civil', 'N', 8);
INSERT INTO consistenciacao.campo_consistenciacao VALUES (13, 'Número folha certidão civil', 'N', 4);
INSERT INTO consistenciacao.campo_consistenciacao VALUES (14, 'Data emissão certidão civil', 'N', 20);
INSERT INTO consistenciacao.campo_consistenciacao VALUES (15, 'Cartório emissor certidão civil', 'N', 150);
INSERT INTO consistenciacao.campo_consistenciacao VALUES (16, 'UF emissão certidão civil', 'S', 30);
INSERT INTO consistenciacao.campo_consistenciacao VALUES (17, 'Número carteira trabalho', 'N', 7);
INSERT INTO consistenciacao.campo_consistenciacao VALUES (18, 'Número série carteira trabalho', 'N', 5);
INSERT INTO consistenciacao.campo_consistenciacao VALUES (19, 'Data emissão carteira trabalho', 'N', 20);
INSERT INTO consistenciacao.campo_consistenciacao VALUES (20, 'UF emissão carteira trabalho', 'S', 30);
INSERT INTO consistenciacao.campo_consistenciacao VALUES (21, 'Número título de eleitor', 'N', 13);
INSERT INTO consistenciacao.campo_consistenciacao VALUES (22, 'Número zona título eleitor', 'N', 4);
INSERT INTO consistenciacao.campo_consistenciacao VALUES (23, 'Número seção título eleitor', 'N', 4);
INSERT INTO consistenciacao.campo_consistenciacao VALUES (24, 'Nome fantasia pessoa jurídica', 'N', 50);
INSERT INTO consistenciacao.campo_consistenciacao VALUES (25, 'Número inscrição estadual', 'N', 10);
INSERT INTO consistenciacao.campo_consistenciacao VALUES (26, 'Sexo pessoa física', 'S', 10);
INSERT INTO consistenciacao.campo_consistenciacao VALUES (27, 'Nome mãe', 'N', 150);
INSERT INTO consistenciacao.campo_consistenciacao VALUES (28, 'Nome pai', 'N', 150);
INSERT INTO consistenciacao.campo_consistenciacao VALUES (29, 'Nome cônjuge', 'N', 150);
INSERT INTO consistenciacao.campo_consistenciacao VALUES (30, 'Nome responsável', 'N', 150);
INSERT INTO consistenciacao.campo_consistenciacao VALUES (31, 'Nome última empresa', 'N', 150);
INSERT INTO consistenciacao.campo_consistenciacao VALUES (32, 'Ocupação profissional', 'S', 250);
INSERT INTO consistenciacao.campo_consistenciacao VALUES (33, 'Escolaridade', 'S', 60);
INSERT INTO consistenciacao.campo_consistenciacao VALUES (34, 'Estado civil', 'S', 15);
INSERT INTO consistenciacao.campo_consistenciacao VALUES (35, 'País de origem(se estrangeiro)', 'S', 60);
INSERT INTO consistenciacao.campo_consistenciacao VALUES (36, 'Data chegada ao Brasil', 'N', 20);
INSERT INTO consistenciacao.campo_consistenciacao VALUES (37, 'Data óbito', 'N', 20);
INSERT INTO consistenciacao.campo_consistenciacao VALUES (38, 'Data união com cônjuge', 'N', 20);
INSERT INTO consistenciacao.campo_consistenciacao VALUES (39, 'DDD telefone residencial', 'N', 3);
INSERT INTO consistenciacao.campo_consistenciacao VALUES (40, 'Telefone residencial', 'N', 8);
INSERT INTO consistenciacao.campo_consistenciacao VALUES (41, 'DDD telefone comercial', 'N', 3);
INSERT INTO consistenciacao.campo_consistenciacao VALUES (42, 'Telefone comercial', 'N', 8);
INSERT INTO consistenciacao.campo_consistenciacao VALUES (43, 'DDD telefone celular', 'N', 3);
INSERT INTO consistenciacao.campo_consistenciacao VALUES (44, 'Telefone celular', 'N', 8);
INSERT INTO consistenciacao.campo_consistenciacao VALUES (45, 'DDD fax', 'N', 3);
INSERT INTO consistenciacao.campo_consistenciacao VALUES (46, 'Fax', 'N', 8);
INSERT INTO consistenciacao.campo_consistenciacao VALUES (47, 'Logradouro (end. correspondência)', 'N', 150);
INSERT INTO consistenciacao.campo_consistenciacao VALUES (48, 'Tipo logradouro (end. correspondência)', 'S', 15);
INSERT INTO consistenciacao.campo_consistenciacao VALUES (49, 'Número (end. correspondência)', 'N', 6);
INSERT INTO consistenciacao.campo_consistenciacao VALUES (50, 'Letra (end. correspondência)', 'N', 1);
INSERT INTO consistenciacao.campo_consistenciacao VALUES (51, 'Complemento (end. correspondência)', 'N', 20);
INSERT INTO consistenciacao.campo_consistenciacao VALUES (52, 'Bairro (end. correspondência)', 'N', 40);
INSERT INTO consistenciacao.campo_consistenciacao VALUES (53, 'CEP (end. correspondência)', 'N', 8);
INSERT INTO consistenciacao.campo_consistenciacao VALUES (54, 'Cidade (end. correspondência)', 'N', 60);
INSERT INTO consistenciacao.campo_consistenciacao VALUES (55, 'UF (end. correspondência)', 'S', 30);
INSERT INTO consistenciacao.campo_consistenciacao VALUES (56, 'Logradouro (end. residencial)', 'N', 150);
INSERT INTO consistenciacao.campo_consistenciacao VALUES (57, 'Tipo logradouro (end. residencial)', 'S', 15);
INSERT INTO consistenciacao.campo_consistenciacao VALUES (58, 'Número (end. residencial)', 'N', 6);
INSERT INTO consistenciacao.campo_consistenciacao VALUES (59, 'Letra (end. residencial)', 'N', 1);
INSERT INTO consistenciacao.campo_consistenciacao VALUES (60, 'Complemento (end. residencial)', 'N', 20);
INSERT INTO consistenciacao.campo_consistenciacao VALUES (61, 'Bairro (end. residencial)', 'N', 40);
INSERT INTO consistenciacao.campo_consistenciacao VALUES (62, 'CEP (end. residencial)', 'N', 8);
INSERT INTO consistenciacao.campo_consistenciacao VALUES (63, 'Cidade (end. residencial)', 'N', 60);
INSERT INTO consistenciacao.campo_consistenciacao VALUES (64, 'UF (end. residencial)', 'S', 30);
INSERT INTO consistenciacao.campo_consistenciacao VALUES (65, 'Logradouro (end. comercial)', 'N', 150);
INSERT INTO consistenciacao.campo_consistenciacao VALUES (66, 'Tipo logradouro (end. comercial)', 'S', 15);
INSERT INTO consistenciacao.campo_consistenciacao VALUES (67, 'Número (end. comercial)', 'N', 6);
INSERT INTO consistenciacao.campo_consistenciacao VALUES (68, 'Letra (end. comercial)', 'N', 1);
INSERT INTO consistenciacao.campo_consistenciacao VALUES (69, 'Complemento (end. comercial)', 'N', 20);
INSERT INTO consistenciacao.campo_consistenciacao VALUES (70, 'Bairro (end. comercial)', 'N', 40);
INSERT INTO consistenciacao.campo_consistenciacao VALUES (71, 'CEP (end. comercial)', 'N', 8);
INSERT INTO consistenciacao.campo_consistenciacao VALUES (72, 'Cidade (end. comercial)', 'N', 60);
INSERT INTO consistenciacao.campo_consistenciacao VALUES (73, 'UF (end. comercial)', 'S', 30);
INSERT INTO consistenciacao.campo_consistenciacao VALUES (74, 'Logradouro (correspondência ou residencial)', 'N', 150);
INSERT INTO consistenciacao.campo_consistenciacao VALUES (75, 'Tipo logradouro (correspondência ou residencial)', 'S', 15);
INSERT INTO consistenciacao.campo_consistenciacao VALUES (76, 'Número (correspondência ou residencial)', 'N', 6);
INSERT INTO consistenciacao.campo_consistenciacao VALUES (77, 'Letra (correspondência ou residencial)', 'N', 1);
INSERT INTO consistenciacao.campo_consistenciacao VALUES (78, 'Complemento (correspondência ou residencial)', 'N', 20);
INSERT INTO consistenciacao.campo_consistenciacao VALUES (79, 'Bairro (correspondência ou residencial)', 'N', 40);
INSERT INTO consistenciacao.campo_consistenciacao VALUES (80, 'CEP (correspondência ou residencial)', 'N', 8);
INSERT INTO consistenciacao.campo_consistenciacao VALUES (81, 'Cidade (correspondência ou residencial)', 'N', 60);
INSERT INTO consistenciacao.campo_consistenciacao VALUES (82, 'UF (correspondência ou residencial)', 'S', 30);
INSERT INTO consistenciacao.campo_consistenciacao VALUES (83, 'Logradouro (correspondência ou comercial)', 'N', 150);
INSERT INTO consistenciacao.campo_consistenciacao VALUES (84, 'Tipo logradouro (correspondência ou comercial)', 'S', 15);
INSERT INTO consistenciacao.campo_consistenciacao VALUES (85, 'Número (correspondência ou comercial)', 'N', 6);
INSERT INTO consistenciacao.campo_consistenciacao VALUES (86, 'Letra (correspondência ou comercial)', 'N', 1);
INSERT INTO consistenciacao.campo_consistenciacao VALUES (87, 'Complemento (correspondência ou comercial)', 'N', 20);
INSERT INTO consistenciacao.campo_consistenciacao VALUES (88, 'Bairro (correspondência ou comercial)', 'N', 40);
INSERT INTO consistenciacao.campo_consistenciacao VALUES (89, 'CEP (correspondência ou comercial)', 'N', 8);
INSERT INTO consistenciacao.campo_consistenciacao VALUES (90, 'Cidade (correspondência ou comercial)', 'N', 60);
INSERT INTO consistenciacao.campo_consistenciacao VALUES (91, 'UF (correspondência ou comercial)', 'S', 30);
INSERT INTO consistenciacao.campo_consistenciacao VALUES (92, 'DDD telefone comercial ou residencial', 'N', 3);
INSERT INTO consistenciacao.campo_consistenciacao VALUES (93, 'Telefone comercial ou residencial', 'N', 8);
INSERT INTO consistenciacao.campo_consistenciacao VALUES (94, 'CPF', 'N', 14);
INSERT INTO consistenciacao.campo_consistenciacao VALUES (95, 'CNPJ', 'N', 14);
