INSERT INTO modules.etapas_educacenso VALUES (1, 'Educação Infantil - Creche (0 a 3 anos)');
INSERT INTO modules.etapas_educacenso VALUES (2, 'Educação Infantil - Pré-escola (4 a 5 anos)');
INSERT INTO modules.etapas_educacenso VALUES (3, 'Ensino Fundamental 8 anos');
INSERT INTO modules.etapas_educacenso VALUES (4, 'Ensino Fundamental 9 anos');
INSERT INTO modules.etapas_educacenso VALUES (5, 'Ensino médio - Médio');
INSERT INTO modules.etapas_educacenso VALUES (6, 'Ensino médio - Integrado');
INSERT INTO modules.etapas_educacenso VALUES (7, 'Ensino médio - Normal/Magistério');
INSERT INTO modules.etapas_educacenso VALUES (8, 'Ensino médio - Educação profissional');
INSERT INTO modules.etapas_educacenso VALUES (9, 'EJA - Ensino fundamental');
INSERT INTO modules.etapas_educacenso VALUES (10, 'EJA - Ensino médio');
INSERT INTO modules.etapas_educacenso VALUES (11, 'EJA - Ensino fundamental - Projovem (urbano)');
