INSERT INTO portal.menu_menu VALUES (1, 'Todos', '', NULL, '#', 9999, false, NULL);
INSERT INTO portal.menu_menu VALUES (23, 'Principal', '', NULL, '#', 9999, false, NULL);
INSERT INTO portal.menu_menu VALUES (38, 'i-Pauta', '', NULL, '#', 9999, false, NULL);
INSERT INTO portal.menu_menu VALUES (56, 'i-Educar - Controle', NULL, NULL, '#', 9999, false, NULL);
INSERT INTO portal.menu_menu VALUES (5, 'Agenda', 'Agendas', NULL, '#', 9999, false, NULL);
INSERT INTO portal.menu_menu VALUES (68, 'Endereçamento', '', NULL, '/intranet/educar_enderecamento_index.php', 2, true, 'fa-map');
INSERT INTO portal.menu_menu VALUES (7, 'Pessoas', 'Pessoas Físicas e Jurídicas', NULL, '/intranet/educar_pessoas_index.php', 3, true, 'fa-user');
INSERT INTO portal.menu_menu VALUES (55, 'Escola', NULL, NULL, '/intranet/educar_index.php', 4, true, 'fa-leanpub');
INSERT INTO portal.menu_menu VALUES (69, 'Transporte escolar', NULL, NULL, '/intranet/educar_transporte_escolar_index.php', 7, true, 'fa-bus');
INSERT INTO portal.menu_menu VALUES (57, 'Biblioteca', NULL, NULL, '/intranet/educar_biblioteca_index.php', 8, true, 'fa-book');
INSERT INTO portal.menu_menu VALUES (25, 'Configurações', 'Sistemas do RH', NULL, '/intranet/educar_configuracoes_index.php', 9, true, 'fa-gear');
INSERT INTO portal.menu_menu VALUES (70, 'Educacenso', NULL, NULL, '/intranet/educar_educacenso_index.php', 6, true, 'fa-bar-chart');
INSERT INTO portal.menu_menu VALUES (71, 'Servidores', '', NULL, '/intranet/educar_servidores_index.php', 5, true, 'fa-users');
