INSERT INTO portal.menu_submenu VALUES (0, 1, 0, 'Super usuário', '', '', 3);
INSERT INTO portal.menu_submenu VALUES (155, 23, 2, 'Minha agenda', 'agenda.php', '', 2);
INSERT INTO portal.menu_submenu VALUES (157, 23, 2, 'Minhas conexões', 'conexoes_lst.php', 'Minhas Conexões', 2);
INSERT INTO portal.menu_submenu VALUES (475, 23, 2, 'Preferências', 'opcao_menu_lst.php', '', 2);
INSERT INTO portal.menu_submenu VALUES (335, 38, 2, 'Super usuário ', 'otopic_su_lst.php', '', 3);
INSERT INTO portal.menu_submenu VALUES (569, 55, 2, 'Material didático', 'educar_material_didatico_lst.php', '', 3);
INSERT INTO portal.menu_submenu VALUES (21235, 69, 2, 'Empresas do transporte', 'transporte_empresa_lst.php', NULL, 3);
INSERT INTO portal.menu_submenu VALUES (21236, 69, 2, 'Motoristas do transporte', 'transporte_motorista_lst.php', NULL, 3);
INSERT INTO portal.menu_submenu VALUES (563, 55, 2, 'Tipo material didático', 'educar_material_tipo_lst.php', '', 3);
INSERT INTO portal.menu_submenu VALUES (21237, 69, 2, 'Veículos do transporte', 'transporte_veiculo_lst.php', NULL, 3);
INSERT INTO portal.menu_submenu VALUES (559, 55, 2, 'Instituição', 'educar_instituicao_lst.php', '', 3);
INSERT INTO portal.menu_submenu VALUES (9998851, 25, 2, 'Auditoria geral', 'educar_auditoria_geral_lst.php', NULL, 3);
INSERT INTO portal.menu_submenu VALUES (9998858, 25, 2, 'Backups', 'educar_backup_lst.php', '', 3);
INSERT INTO portal.menu_submenu VALUES (624, 55, 2, 'Apresentação', 'educar_index.php', '', 2);
INSERT INTO portal.menu_submenu VALUES (946, 55, 2, 'Componentes curriculares', 'educar_componente_curricular_lst.php', '', 3);
INSERT INTO portal.menu_submenu VALUES (9998849, 70, 2, 'Importação educacenso', 'educar_importacao_educacenso.php', NULL, 3);
INSERT INTO portal.menu_submenu VALUES (845, 55, 2, 'Rematrícula automática', 'educar_avancar_mod_cad.php', 'Rematrícula Automática', 3);
INSERT INTO portal.menu_submenu VALUES (9998859, 55, 2, 'Componentes da série', 'educar_componentes_serie_lst.php', NULL, 3);
INSERT INTO portal.menu_submenu VALUES (606, 57, 2, 'Exemplares', 'educar_exemplar_lst.php', '', 3);
INSERT INTO portal.menu_submenu VALUES (602, 57, 2, 'Situação', 'educar_situacao_lst.php', '', 3);
INSERT INTO portal.menu_submenu VALUES (598, 57, 2, 'Obras', 'educar_acervo_lst.php', '', 3);
INSERT INTO portal.menu_submenu VALUES (625, 57, 2, 'Apresentação', 'educar_biblioteca_index.php', '', 2);
INSERT INTO portal.menu_submenu VALUES (947, 55, 2, 'Regras de avaliação', 'module/RegraAvaliacao/index', '', 3);
INSERT INTO portal.menu_submenu VALUES (949, 55, 2, 'Tabelas de arredondamento de nota', 'module/TabelaArredondamento/index', '', 3);
INSERT INTO portal.menu_submenu VALUES (341, 5, 2, 'Agendas', 'agenda_responsavel.php', NULL, 2);
INSERT INTO portal.menu_submenu VALUES (343, 5, 2, 'Agenda admin', 'agenda_admin_lst.php', NULL, 3);
INSERT INTO portal.menu_submenu VALUES (345, 5, 2, 'Agenda pessoal', 'agenda.php', 'Agenda pessoal', 2);
INSERT INTO portal.menu_submenu VALUES (21234, 69, 2, 'Apresentação', 'transporte_index.php', NULL, 2);
INSERT INTO portal.menu_submenu VALUES (634, 71, 2, 'Funções do servidor', 'educar_funcao_lst.php', '', 3);
INSERT INTO portal.menu_submenu VALUES (632, 71, 2, 'Escolaridade do servidor', 'educar_escolaridade_lst.php', '', 3);
INSERT INTO portal.menu_submenu VALUES (829, 71, 2, 'Categoria ou níveis do servidor', 'educar_categoria_nivel_lst.php', '', 3);
INSERT INTO portal.menu_submenu VALUES (633, 71, 2, 'Motivos de afastamento do servidor', 'educar_motivo_afastamento_lst.php', '', 3);
INSERT INTO portal.menu_submenu VALUES (635, 71, 2, 'Servidores', 'educar_servidor_lst.php', '', 3);
INSERT INTO portal.menu_submenu VALUES (641, 71, 2, 'Quadros de horários', 'educar_quadro_horario_lst.php', '', 3);
INSERT INTO portal.menu_submenu VALUES (948, 55, 2, 'Fórmulas de cálculo de média', 'module/FormulaMedia/index', '', 3);
INSERT INTO portal.menu_submenu VALUES (577, 55, 2, 'Tipos de dispensa da disciplina', 'educar_tipo_dispensa_lst.php', '', 3);
INSERT INTO portal.menu_submenu VALUES (43, 7, 2, 'Pessoas físicas', 'atendidos_lst.php', '', 3);
INSERT INTO portal.menu_submenu VALUES (41, 7, 2, 'Pessoas jurídicas', 'empresas_lst.php', '', 3);
INSERT INTO portal.menu_submenu VALUES (753, 68, 2, 'Países', 'public_pais_lst.php', '', 3);
INSERT INTO portal.menu_submenu VALUES (754, 68, 2, 'Estados', 'public_uf_lst.php', '', 3);
INSERT INTO portal.menu_submenu VALUES (755, 68, 2, 'Municípios', 'public_municipio_lst.php', '', 3);
INSERT INTO portal.menu_submenu VALUES (759, 68, 2, 'Distritos', 'public_distrito_lst.php', NULL, 3);
INSERT INTO portal.menu_submenu VALUES (756, 68, 2, 'Bairros', 'public_bairro_lst.php', '', 3);
INSERT INTO portal.menu_submenu VALUES (757, 68, 2, 'Logradouros', 'public_logradouro_lst.php', '', 3);
INSERT INTO portal.menu_submenu VALUES (758, 68, 2, 'CEP', 'urbano_cep_logradouro_lst.php', '', 3);
INSERT INTO portal.menu_submenu VALUES (581, 55, 2, 'Tipos de benefício do aluno', 'educar_aluno_beneficio_lst.php', '', 3);
INSERT INTO portal.menu_submenu VALUES (575, 55, 2, 'Tipos de transferência da matrícula', 'educar_transferencia_tipo_lst.php', '', 3);
INSERT INTO portal.menu_submenu VALUES (580, 55, 2, 'Tipos de ocorrência disciplinar da matrícula', 'educar_tipo_ocorrencia_disciplinar_lst.php', '', 3);
INSERT INTO portal.menu_submenu VALUES (945, 55, 2, 'Áreas de conhecimento da disciplina', 'module/AreaConhecimento/index', '', 3);
INSERT INTO portal.menu_submenu VALUES (573, 55, 2, 'Tipos de habilitação do curso', 'educar_habilitacao_lst.php', '', 3);
INSERT INTO portal.menu_submenu VALUES (568, 55, 2, 'Tipos de regime do curso', 'educar_tipo_regime_lst.php', '', 3);
INSERT INTO portal.menu_submenu VALUES (558, 55, 2, 'Tipos de ensino do curso', 'educar_tipo_ensino_lst.php', '', 3);
INSERT INTO portal.menu_submenu VALUES (571, 55, 2, 'Tipos de nível ensino do curso', 'educar_nivel_ensino_lst.php', '', 3);
INSERT INTO portal.menu_submenu VALUES (562, 55, 2, 'Tipos de localização da escola', 'educar_escola_localizacao_lst.php', '', 3);
INSERT INTO portal.menu_submenu VALUES (659, 55, 2, 'Enturmações em lote', 'educar_matriculas_turma_lst.php', '', 3);
INSERT INTO portal.menu_submenu VALUES (678, 7, 2, 'Tipos de cor ou raça da pessoa', 'educar_raca_lst.php', '', 3);
INSERT INTO portal.menu_submenu VALUES (631, 7, 2, 'Tipos de deficiência da pessoa', 'educar_deficiencia_lst.php', '', 3);
INSERT INTO portal.menu_submenu VALUES (579, 7, 2, 'Tipos de religião da pessoa', 'educar_religiao_lst.php', '', 3);
INSERT INTO portal.menu_submenu VALUES (21240, 69, 2, 'Usuários de transporte', 'transporte_pessoa_lst.php', NULL, 3);
INSERT INTO portal.menu_submenu VALUES (21238, 69, 2, 'Rotas do transporte', 'transporte_rota_lst.php', NULL, 3);
INSERT INTO portal.menu_submenu VALUES (21239, 69, 2, 'Pontos do transporte', 'transporte_ponto_lst.php', NULL, 3);
INSERT INTO portal.menu_submenu VALUES (21251, 55, 2, 'Bloqueio do ano letivo', 'educar_bloqueio_ano_letivo_lst.php', '', 3);
INSERT INTO portal.menu_submenu VALUES (642, 55, 2, 'Lançamento de faltas e notas', 'module/Avaliacao/diario', '', 3);
INSERT INTO portal.menu_submenu VALUES (21250, 55, 2, 'Tipos de projeto do aluno', 'educar_projeto_lst.php', '', 3);
INSERT INTO portal.menu_submenu VALUES (950, 55, 2, 'Tipos de abandono da matrícula', 'educar_abandono_tipo_lst.php', NULL, 3);
INSERT INTO portal.menu_submenu VALUES (572, 55, 2, 'Tipos de ambiente da escola', 'educar_infra_comodo_funcao_lst.php', '', 3);
INSERT INTO portal.menu_submenu VALUES (574, 55, 2, 'Infraestrutura da escola', 'educar_infra_predio_comodo_lst.php', '', 3);
INSERT INTO portal.menu_submenu VALUES (21246, 69, 2, 'Cópia de rotas do transporte', 'transporte_copia_rotas.php', NULL, 3);
INSERT INTO portal.menu_submenu VALUES (761, 68, 2, 'Unificação de bairros', 'educar_unifica_bairro.php', NULL, 3);
INSERT INTO portal.menu_submenu VALUES (762, 68, 2, 'Unificação de logradouros', 'educar_unifica_logradouro.php', NULL, 3);
INSERT INTO portal.menu_submenu VALUES (626, 55, 0, 'Alterar datas de entrada/saída de matrículas', '', NULL, 3);
INSERT INTO portal.menu_submenu VALUES (627, 55, 0, 'Cancelar matrícula', '', NULL, 3);
INSERT INTO portal.menu_submenu VALUES (21253, 55, 2, 'Vagas por série/ano', 'educar_serie_vaga_lst.php', '', 3);
INSERT INTO portal.menu_submenu VALUES (999847, 55, 2, 'Unificação de alunos', 'educar_unifica_aluno.php', NULL, 3);
INSERT INTO portal.menu_submenu VALUES (630, 55, 0, 'Alterar média final do aluno e situação (para regras de avaliação manuais)', '', NULL, 3);
INSERT INTO portal.menu_submenu VALUES (999849, 55, 0, 'Permitir lançamento de notas/faltas fora do período de bloqueio por etapa', '', NULL, 3);
INSERT INTO portal.menu_submenu VALUES (554, 25, 2, 'Tipos de usuário', 'educar_tipo_usuario_lst.php', '', 3);
INSERT INTO portal.menu_submenu VALUES (555, 25, 2, 'Usuários', 'educar_usuario_lst.php', '', 3);
INSERT INTO portal.menu_submenu VALUES (644, 25, 2, 'Atualização de matrículas', 'module/Avaliacao/Promocao', '', 3);
INSERT INTO portal.menu_submenu VALUES (760, 68, 2, 'Setores', 'public_setor_lst.php', NULL, 3);
INSERT INTO portal.menu_submenu VALUES (999873, 25, 2, 'Configurações gerais', 'educar_configuracoes_gerais.php', NULL, 3);
INSERT INTO portal.menu_submenu VALUES (999878, 55, 0, 'Permitir editar endereço no cadastro de pessoa física', '', NULL, 3);
INSERT INTO portal.menu_submenu VALUES (592, 57, 2, 'Assuntos de obras', 'educar_acervo_assunto_lst.php', '', 3);
INSERT INTO portal.menu_submenu VALUES (594, 57, 2, 'Autores de obras', 'educar_acervo_autor_lst.php', '', 3);
INSERT INTO portal.menu_submenu VALUES (593, 57, 2, 'Coleções de obras', 'educar_acervo_colecao_lst.php', '', 3);
INSERT INTO portal.menu_submenu VALUES (595, 57, 2, 'Editoras de obras', 'educar_acervo_editora_lst.php', '', 3);
INSERT INTO portal.menu_submenu VALUES (590, 57, 2, 'Idiomas de obras', 'educar_acervo_idioma_lst.php', '', 3);
INSERT INTO portal.menu_submenu VALUES (608, 57, 2, 'Fontes de obras', 'educar_fonte_lst.php', '', 3);
INSERT INTO portal.menu_submenu VALUES (597, 57, 2, 'Tipos de exemplar', 'educar_exemplar_tipo_lst.php', '', 3);
INSERT INTO portal.menu_submenu VALUES (15891, 57, 2, 'Tipos de situação de exemplar', 'educar_situacao_lst.php', NULL, 3);
INSERT INTO portal.menu_submenu VALUES (600, 57, 2, 'Motivos de baixa do exemplar', 'educar_motivo_baixa_lst.php', '', 3);
INSERT INTO portal.menu_submenu VALUES (596, 57, 2, 'Tipos de cliente', 'educar_cliente_tipo_lst.php', '', 3);
INSERT INTO portal.menu_submenu VALUES (607, 57, 2, 'Motivos de suspensão do cliente', 'educar_motivo_suspensao_lst.php', '', 3);
INSERT INTO portal.menu_submenu VALUES (591, 57, 2, 'Bibliotecas', 'educar_biblioteca_lst.php', '', 3);
INSERT INTO portal.menu_submenu VALUES (603, 57, 2, 'Clientes', 'educar_cliente_lst.php', '', 3);
INSERT INTO portal.menu_submenu VALUES (629, 57, 2, 'Configurações de bibliotecas', 'educar_biblioteca_dados_lst.php', '', 3);
INSERT INTO portal.menu_submenu VALUES (609, 57, 2, 'Reservas de exemplares', 'educar_reservas_lst.php', '', 3);
INSERT INTO portal.menu_submenu VALUES (610, 57, 2, 'Empréstimos de exemplares', 'module/Biblioteca/emprestimo', '', 3);
INSERT INTO portal.menu_submenu VALUES (628, 57, 2, 'Devoluções de exemplares', 'educar_exemplar_devolucao_lst.php', '', 3);
INSERT INTO portal.menu_submenu VALUES (622, 57, 2, 'Dívidas de exemplares', 'educar_pagamento_multa_lst.php', '', 3);
INSERT INTO portal.menu_submenu VALUES (999869, 25, 2, 'Exportação de usuários', 'educar_exportacao_usuarios.php', NULL, 3);
INSERT INTO portal.menu_submenu VALUES (587, 55, 2, 'Sequências de enturmação', 'educar_sequencia_serie_lst.php', '', 3);
INSERT INTO portal.menu_submenu VALUES (570, 55, 2, 'Tipos de turma', 'educar_turma_tipo_lst.php', '', 3);
INSERT INTO portal.menu_submenu VALUES (567, 55, 2, 'Prédios da escola', 'educar_infra_predio_lst.php', '', 3);
INSERT INTO portal.menu_submenu VALUES (576, 55, 2, 'Tipos de evento do calendário', 'educar_calendario_dia_motivo_lst.php', '', 3);
INSERT INTO portal.menu_submenu VALUES (561, 55, 2, 'Escolas', 'educar_escola_lst.php', '', 3);
INSERT INTO portal.menu_submenu VALUES (566, 55, 2, 'Cursos', 'educar_curso_lst.php', '', 3);
INSERT INTO portal.menu_submenu VALUES (578, 55, 2, 'Alunos', 'educar_aluno_lst.php', '', 3);
INSERT INTO portal.menu_submenu VALUES (647, 55, 2, 'Tipos de rede de ensino da escola', 'educar_escola_rede_ensino_lst.php', '', 3);
INSERT INTO portal.menu_submenu VALUES (999867, 57, 2, 'Categorias de obras', 'educar_categoria_lst.php', NULL, 3);
INSERT INTO portal.menu_submenu VALUES (846, 70, 2, 'Exportação do educacenso - 1ª fase', 'educar_exportacao_educacenso.php', NULL, 2);
INSERT INTO portal.menu_submenu VALUES (9998845, 70, 2, 'Exportação do educacenso - 2ª fase', 'educar_exportacao_educacenso.php?fase2=1', NULL, 2);
INSERT INTO portal.menu_submenu VALUES (999861, 55, 2, 'Documentação padrão', 'DocumentacaoPadrao.php', NULL, 3);
INSERT INTO portal.menu_submenu VALUES (583, 55, 2, 'Séries', 'educar_serie_lst.php', '', 3);
INSERT INTO portal.menu_submenu VALUES (586, 55, 2, 'Turmas', 'educar_turma_lst.php', '', 3);
INSERT INTO portal.menu_submenu VALUES (620, 55, 2, 'Calendários', 'educar_calendario_ano_letivo_lst.php', '', 3);
INSERT INTO portal.menu_submenu VALUES (21145, 55, 2, 'Lançamento de ocorrências disciplinares', 'educar_matricula_ocorrencia_disciplinar_cad.php', NULL, 3);
INSERT INTO portal.menu_submenu VALUES (999613, 55, 2, 'Processamento de históricos escolares', 'module/HistoricoEscolar/processamento', NULL, 3);
INSERT INTO portal.menu_submenu VALUES (999848, 55, 2, 'Bloqueio de lançamento de notas e faltas', 'educar_bloqueio_lancamento_faltas_notas_lst.php', NULL, 3);
INSERT INTO portal.menu_submenu VALUES (585, 55, 2, 'Séries da escola', 'educar_escola_serie_lst.php', '', 3);
INSERT INTO portal.menu_submenu VALUES (9998867, 25, 2, 'Configuração movimento geral', 'module/Configuracao/ConfiguracaoMovimentoGeral', NULL, 3);
INSERT INTO portal.menu_submenu VALUES (9998869, 25, 2, 'Customização de labels', 'educar_configuracoes_labels.php', NULL, 3);
INSERT INTO portal.menu_submenu VALUES (9998878, 7, 2, 'Unificação de pessoas', 'educar_unifica_pessoa.php', NULL, 3);
INSERT INTO portal.menu_submenu VALUES (584, 55, 2, 'Tipos de etapas da escola', 'educar_modulo_lst.php', '', 3);
INSERT INTO portal.menu_submenu VALUES (9998900, 55, 2, 'Consulta de movimento geral', 'educar_consulta_movimento_geral.php', NULL, 3);
INSERT INTO portal.menu_submenu VALUES (9998910, 55, 2, 'Consulta de movimento mensal', 'educar_consulta_movimento_mensal.php', NULL, 3);
INSERT INTO portal.menu_submenu VALUES (190, 71, 2, 'Vínculos da alocação', 'funcionario_vinculo_lst.php', NULL, 3);
