INSERT INTO public.uf VALUES ('RO', 'Rondônia', NULL, 45, 11);
INSERT INTO public.uf VALUES ('AC', 'Acre', NULL, 45, 12);
INSERT INTO public.uf VALUES ('AM', 'Amazonas', NULL, 45, 13);
INSERT INTO public.uf VALUES ('RR', 'Roraima', NULL, 45, 14);
INSERT INTO public.uf VALUES ('PA', 'Pará', NULL, 45, 15);
INSERT INTO public.uf VALUES ('AP', 'Amapá', NULL, 45, 16);
INSERT INTO public.uf VALUES ('TO', 'Tocantins', NULL, 45, 17);
INSERT INTO public.uf VALUES ('MA', 'Maranhão', NULL, 45, 21);
INSERT INTO public.uf VALUES ('PI', 'Piauí', NULL, 45, 22);
INSERT INTO public.uf VALUES ('CE', 'Ceará', NULL, 45, 23);
INSERT INTO public.uf VALUES ('RN', 'Rio Grande do Norte', NULL, 45, 24);
INSERT INTO public.uf VALUES ('PB', 'Paraíba', NULL, 45, 25);
INSERT INTO public.uf VALUES ('PE', 'Pernambuco', NULL, 45, 26);
INSERT INTO public.uf VALUES ('AL', 'Alagoas', NULL, 45, 27);
INSERT INTO public.uf VALUES ('SE', 'Sergipe', NULL, 45, 28);
INSERT INTO public.uf VALUES ('BA', 'Bahia', NULL, 45, 29);
INSERT INTO public.uf VALUES ('MG', 'Minas Gerais', NULL, 45, 31);
INSERT INTO public.uf VALUES ('ES', 'Espírito Santo', NULL, 45, 32);
INSERT INTO public.uf VALUES ('RJ', 'Rio de Janeiro', NULL, 45, 33);
INSERT INTO public.uf VALUES ('SP', 'São Paulo', NULL, 45, 35);
INSERT INTO public.uf VALUES ('PR', 'Paraná', NULL, 45, 41);
INSERT INTO public.uf VALUES ('SC', 'Santa Catarina', NULL, 45, 42);
INSERT INTO public.uf VALUES ('RS', 'Rio Grande do Sul', NULL, 45, 43);
INSERT INTO public.uf VALUES ('MS', 'Mato Grosso do Sul', NULL, 45, 50);
INSERT INTO public.uf VALUES ('MT', 'Mato Grosso', NULL, 45, 51);
INSERT INTO public.uf VALUES ('GO', 'Goiás', NULL, 45, 52);
INSERT INTO public.uf VALUES ('DF', 'Distrito Federal', NULL, 45, 53);
