INSERT INTO public.etapa_educacenso (id, name) VALUES (1, 'Educação Infantil - Creche (0 a 3 anos)');
INSERT INTO public.etapa_educacenso (id, name) VALUES (2, 'Educação Infantil - Pré-escola (4 e 5 anos)');
INSERT INTO public.etapa_educacenso (id, name) VALUES (3, 'Educação Infantil - Unificada (0 a 5 anos)');
INSERT INTO public.etapa_educacenso (id, name) VALUES (14, 'Ensino Fundamental de 9 anos - 1º Ano');
INSERT INTO public.etapa_educacenso (id, name) VALUES (15, 'Ensino Fundamental de 9 anos - 2º Ano');
INSERT INTO public.etapa_educacenso (id, name) VALUES (16, 'Ensino Fundamental de 9 anos - 3º Ano');
INSERT INTO public.etapa_educacenso (id, name) VALUES (17, 'Ensino Fundamental de 9 anos - 4º Ano');
INSERT INTO public.etapa_educacenso (id, name) VALUES (18, 'Ensino Fundamental de 9 anos - 5º Ano');
INSERT INTO public.etapa_educacenso (id, name) VALUES (19, 'Ensino Fundamental de 9 anos - 6º Ano');
INSERT INTO public.etapa_educacenso (id, name) VALUES (20, 'Ensino Fundamental de 9 anos - 7º Ano');
INSERT INTO public.etapa_educacenso (id, name) VALUES (21, 'Ensino Fundamental de 9 anos - 8º Ano');
INSERT INTO public.etapa_educacenso (id, name) VALUES (22, 'Ensino Fundamental de 9 anos - Multi');
INSERT INTO public.etapa_educacenso (id, name) VALUES (23, 'Ensino Fundamental de 9 anos - Correção de Fluxo');
INSERT INTO public.etapa_educacenso (id, name) VALUES (24, 'Ensino Fundamental de 8 e 9 anos - Multi 8 e 9 anos');
INSERT INTO public.etapa_educacenso (id, name) VALUES (25, 'Ensino Médio - 1ª Série');
INSERT INTO public.etapa_educacenso (id, name) VALUES (26, 'Ensino Médio - 2ª Série');
INSERT INTO public.etapa_educacenso (id, name) VALUES (27, 'Ensino Médio - 3ª Série');
INSERT INTO public.etapa_educacenso (id, name) VALUES (28, 'Ensino Médio - 4ª Série');
INSERT INTO public.etapa_educacenso (id, name) VALUES (29, 'Ensino Médio - Não Seriada');
INSERT INTO public.etapa_educacenso (id, name) VALUES (30, 'Curso Técnico Integrado (Ensino Médio Integrado) 1ª Série');
INSERT INTO public.etapa_educacenso (id, name) VALUES (31, 'Curso Técnico Integrado (Ensino Médio Integrado) 2ª Série');
INSERT INTO public.etapa_educacenso (id, name) VALUES (32, 'Curso Técnico Integrado (Ensino Médio Integrado) 3ª Série');
INSERT INTO public.etapa_educacenso (id, name) VALUES (33, 'Curso Técnico Integrado (Ensino Médio Integrado) 4ª Série');
INSERT INTO public.etapa_educacenso (id, name) VALUES (34, 'Curso Técnico Integrado (Ensino Médio Integrado) Não Seriada');
INSERT INTO public.etapa_educacenso (id, name) VALUES (35, 'Ensino Médio - Normal/Magistério 1ª Série');
INSERT INTO public.etapa_educacenso (id, name) VALUES (36, 'Ensino Médio - Normal/Magistério 2ª Série');
INSERT INTO public.etapa_educacenso (id, name) VALUES (37, 'Ensino Médio - Normal/Magistério 3ª Série');
INSERT INTO public.etapa_educacenso (id, name) VALUES (38, 'Ensino Médio - Normal/Magistério 4ª Série');
INSERT INTO public.etapa_educacenso (id, name) VALUES (39, 'Curso Técnico - Concomitante');
INSERT INTO public.etapa_educacenso (id, name) VALUES (40, 'Curso Técnico - Subsequente');
INSERT INTO public.etapa_educacenso (id, name) VALUES (41, 'Ensino Fundamental de 9 anos - 9º Ano');
INSERT INTO public.etapa_educacenso (id, name) VALUES (69, 'EJA - Ensino Fundamental - Anos iniciais');
INSERT INTO public.etapa_educacenso (id, name) VALUES (70, 'EJA - Ensino Fundamental - Anos finais');
INSERT INTO public.etapa_educacenso (id, name) VALUES (71, 'EJA - Ensino Médio');
INSERT INTO public.etapa_educacenso (id, name) VALUES (72, 'EJA - Ensino Fundamental - Anos iniciais e Anos finais');
INSERT INTO public.etapa_educacenso (id, name) VALUES (56, 'Educação Infantil e Ensino Fundamental de 9 anos - Multietapa');
INSERT INTO public.etapa_educacenso (id, name) VALUES (73, 'Curso FIC integrado na modalidade EJA - Nível Fundamental (EJA integrada à Educação Profissional de Nível Fundamental)');
INSERT INTO public.etapa_educacenso (id, name) VALUES (74, 'Curso Técnico Integrado na Modalidade EJA (EJA integrada à Educação Profissional de Nível Médio)');
INSERT INTO public.etapa_educacenso (id, name) VALUES (64, 'Curso Técnico Misto');
INSERT INTO public.etapa_educacenso (id, name) VALUES (67, 'Curso FIC integrado na modalidade EJA - Nível Médio');
INSERT INTO public.etapa_educacenso (id, name) VALUES (68, 'Curso FIC Concomitant');
