INSERT INTO public.pais VALUES (1, 'Abissínia', NULL, NULL);
INSERT INTO public.pais VALUES (2, 'Açores', NULL, NULL);
INSERT INTO public.pais VALUES (3, 'Afar Francês', NULL, NULL);
INSERT INTO public.pais VALUES (7, 'Alto Volta', NULL, NULL);
INSERT INTO public.pais VALUES (10, 'Antártica Francesa', NULL, NULL);
INSERT INTO public.pais VALUES (11, 'Antártico Argentino', NULL, NULL);
INSERT INTO public.pais VALUES (12, 'Antártico Britânico, Território', NULL, NULL);
INSERT INTO public.pais VALUES (13, 'Antártico Chileno', NULL, NULL);
INSERT INTO public.pais VALUES (14, 'Antártico Noruegues', NULL, NULL);
INSERT INTO public.pais VALUES (15, 'Antígua E. Dep. Barbuda', NULL, NULL);
INSERT INTO public.pais VALUES (22, 'Arquipélago de Bismark', NULL, NULL);
INSERT INTO public.pais VALUES (23, 'Arquipélago Manahiki', NULL, NULL);
INSERT INTO public.pais VALUES (24, 'Arquipélago Midway', NULL, NULL);
INSERT INTO public.pais VALUES (26, 'Ascensão e Tristão da Cunha,is', NULL, NULL);
INSERT INTO public.pais VALUES (27, 'Ashmore e Cartier', NULL, NULL);
INSERT INTO public.pais VALUES (34, 'Bashkista', NULL, NULL);
INSERT INTO public.pais VALUES (35, 'Bechuanalândia', NULL, NULL);
INSERT INTO public.pais VALUES (38, 'Benin', NULL, NULL);
INSERT INTO public.pais VALUES (40, 'Bhutan', NULL, NULL);
INSERT INTO public.pais VALUES (41, 'Birmânia', NULL, NULL);
INSERT INTO public.pais VALUES (43, 'Bósnia Herzegovina', NULL, NULL);
INSERT INTO public.pais VALUES (44, 'Botsuana', NULL, NULL);
INSERT INTO public.pais VALUES (48, 'Burkina Fasso', NULL, NULL);
INSERT INTO public.pais VALUES (50, 'Buryat', NULL, NULL);
INSERT INTO public.pais VALUES (54, 'Carélia', NULL, NULL);
INSERT INTO public.pais VALUES (57, 'Ceilão', NULL, NULL);
INSERT INTO public.pais VALUES (58, 'Ceuta e Melilla', NULL, NULL);
INSERT INTO public.pais VALUES (60, 'Chechen Ingusth', NULL, NULL);
INSERT INTO public.pais VALUES (63, 'China (taiwan)', NULL, NULL);
INSERT INTO public.pais VALUES (65, 'Chuvash', NULL, NULL);
INSERT INTO public.pais VALUES (68, 'Comunidade das Bahamas', NULL, NULL);
INSERT INTO public.pais VALUES (69, 'Comunidade Dominicana', NULL, NULL);
INSERT INTO public.pais VALUES (70, 'Congo', NULL, NULL);
INSERT INTO public.pais VALUES (71, 'Coréia', NULL, NULL);
INSERT INTO public.pais VALUES (74, 'Coveite', NULL, NULL);
INSERT INTO public.pais VALUES (78, 'Dagesta', NULL, NULL);
INSERT INTO public.pais VALUES (79, 'Daomé', NULL, NULL);
INSERT INTO public.pais VALUES (80, 'Dependência de Ross', NULL, NULL);
INSERT INTO public.pais VALUES (82, 'Djibuti', NULL, NULL);
INSERT INTO public.pais VALUES (83, 'Eire', NULL, NULL);
INSERT INTO public.pais VALUES (86, 'Escócia', NULL, NULL);
INSERT INTO public.pais VALUES (90, 'Estado da Cidade do Vaticano', NULL, NULL);
INSERT INTO public.pais VALUES (91, 'Estados Assoc. das Antilhas', NULL, NULL);
INSERT INTO public.pais VALUES (100, 'Gaza', NULL, NULL);
INSERT INTO public.pais VALUES (103, 'Gorno Altai', NULL, NULL);
INSERT INTO public.pais VALUES (104, 'Grã-bretanha', NULL, NULL);
INSERT INTO public.pais VALUES (110, 'Guiana Francesa', NULL, NULL);
INSERT INTO public.pais VALUES (112, 'Guiné Bissau', NULL, NULL);
INSERT INTO public.pais VALUES (116, 'Honduras Britânicas', NULL, NULL);
INSERT INTO public.pais VALUES (117, 'Hong-kong', NULL, NULL);
INSERT INTO public.pais VALUES (119, 'Iemen', NULL, NULL);
INSERT INTO public.pais VALUES (120, 'Iemen do Sul', NULL, NULL);
INSERT INTO public.pais VALUES (121, 'Ifni', NULL, NULL);
INSERT INTO public.pais VALUES (122, 'Ilha Johnston e Sand', NULL, NULL);
INSERT INTO public.pais VALUES (123, 'Ilha Milhos', NULL, NULL);
INSERT INTO public.pais VALUES (124, 'Ilhas Baker', NULL, NULL);
INSERT INTO public.pais VALUES (125, 'Ilhas Baleares', NULL, NULL);
INSERT INTO public.pais VALUES (126, 'Ilhas Canárias', NULL, NULL);
INSERT INTO public.pais VALUES (127, 'Ilhas Cantão e Enderburg', NULL, NULL);
INSERT INTO public.pais VALUES (128, 'Ilhas Carolinas', NULL, NULL);
INSERT INTO public.pais VALUES (129, 'Ilhas Christmas', NULL, NULL);
INSERT INTO public.pais VALUES (130, 'Ilhas Comores', NULL, NULL);
INSERT INTO public.pais VALUES (132, 'Ilhas Cosmoledo (lomores)', NULL, NULL);
INSERT INTO public.pais VALUES (133, 'Ilhas de Man', NULL, NULL);
INSERT INTO public.pais VALUES (135, 'Ilhas do Pacífico', NULL, NULL);
INSERT INTO public.pais VALUES (136, 'Ilhas Falklands', NULL, NULL);
INSERT INTO public.pais VALUES (137, 'Ilhas Faroes', NULL, NULL);
INSERT INTO public.pais VALUES (138, 'Ilhas Gilbert', NULL, NULL);
INSERT INTO public.pais VALUES (139, 'Ilhas Guadalupe', NULL, NULL);
INSERT INTO public.pais VALUES (140, 'Ilhas Howland e Jarvis', NULL, NULL);
INSERT INTO public.pais VALUES (141, 'Ilhas Kingman Reef', NULL, NULL);
INSERT INTO public.pais VALUES (142, 'Ilhas Linha', NULL, NULL);
INSERT INTO public.pais VALUES (143, 'Ilhas Macdonal e Heard', NULL, NULL);
INSERT INTO public.pais VALUES (144, 'Ilhas Macquaire', NULL, NULL);
INSERT INTO public.pais VALUES (146, 'Ilhas Marianas', NULL, NULL);
INSERT INTO public.pais VALUES (148, 'Ilhas Niue', NULL, NULL);
INSERT INTO public.pais VALUES (149, 'Ilhas Norfolk', NULL, NULL);
INSERT INTO public.pais VALUES (150, 'Ilhas Nova Caledônia', NULL, NULL);
INSERT INTO public.pais VALUES (151, 'Ilhas Novas Hebridas', NULL, NULL);
INSERT INTO public.pais VALUES (152, 'Ilhas Palau', NULL, NULL);
INSERT INTO public.pais VALUES (153, 'Ilhas Páscoa', NULL, NULL);
INSERT INTO public.pais VALUES (154, 'Ilhas Pitcairin', NULL, NULL);
INSERT INTO public.pais VALUES (156, 'Ilhas Santa Cruz', NULL, NULL);
INSERT INTO public.pais VALUES (157, 'Ilhas Serranas', NULL, NULL);
INSERT INTO public.pais VALUES (158, 'Ilhas Tokelau', NULL, NULL);
INSERT INTO public.pais VALUES (159, 'Ilhas Turca', NULL, NULL);
INSERT INTO public.pais VALUES (160, 'Ilhas Turks e Caicos', NULL, NULL);
INSERT INTO public.pais VALUES (163, 'Ilhas Wake', NULL, NULL);
INSERT INTO public.pais VALUES (164, 'Ilhas Wallis e Futuna', NULL, NULL);
INSERT INTO public.pais VALUES (165, 'índia', NULL, NULL);
INSERT INTO public.pais VALUES (167, 'Inglaterra', NULL, NULL);
INSERT INTO public.pais VALUES (171, 'Irlanda do Norte', NULL, NULL);
INSERT INTO public.pais VALUES (175, 'Iugoslávia', NULL, NULL);
INSERT INTO public.pais VALUES (179, 'Kabardino Balkar', NULL, NULL);
INSERT INTO public.pais VALUES (180, 'Kalimatan', NULL, NULL);
INSERT INTO public.pais VALUES (181, 'Kalmir', NULL, NULL);
INSERT INTO public.pais VALUES (182, 'Kara Kalpak', NULL, NULL);
INSERT INTO public.pais VALUES (183, 'Karachaevocherkess', NULL, NULL);
INSERT INTO public.pais VALUES (184, 'Khakass', NULL, NULL);
INSERT INTO public.pais VALUES (185, 'Kmer/camboja', NULL, NULL);
INSERT INTO public.pais VALUES (186, 'Komi', NULL, NULL);
INSERT INTO public.pais VALUES (187, 'Kuwait', NULL, NULL);
INSERT INTO public.pais VALUES (190, 'Letônia', NULL, NULL);
INSERT INTO public.pais VALUES (198, 'Madagascar', NULL, NULL);
INSERT INTO public.pais VALUES (199, 'Madeira', NULL, NULL);
INSERT INTO public.pais VALUES (202, 'Maldivas,is', NULL, NULL);
INSERT INTO public.pais VALUES (204, 'Mari', NULL, NULL);
INSERT INTO public.pais VALUES (207, 'Mascate', NULL, NULL);
INSERT INTO public.pais VALUES (208, 'Maurício', NULL, NULL);
INSERT INTO public.pais VALUES (211, 'Mianma', NULL, NULL);
INSERT INTO public.pais VALUES (216, 'Monte Serrat', NULL, NULL);
INSERT INTO public.pais VALUES (221, 'Nguane', NULL, NULL);
INSERT INTO public.pais VALUES (225, 'Nova Guiné', NULL, NULL);
INSERT INTO public.pais VALUES (227, 'Oman', NULL, NULL);
INSERT INTO public.pais VALUES (228, 'Ossetia Setentrional', NULL, NULL);
INSERT INTO public.pais VALUES (229, 'País de Gales', NULL, NULL);
INSERT INTO public.pais VALUES (230, 'Países Baixos', NULL, NULL);
INSERT INTO public.pais VALUES (233, 'Panamá - Zona do Canal', NULL, NULL);
INSERT INTO public.pais VALUES (234, 'Papua Nova Guiné', NULL, NULL);
INSERT INTO public.pais VALUES (242, 'Praças Norte Africanas', NULL, NULL);
INSERT INTO public.pais VALUES (243, 'Protetor do Sudoeste Africano', NULL, NULL);
INSERT INTO public.pais VALUES (244, 'Quênia', NULL, NULL);
INSERT INTO public.pais VALUES (245, 'Quirguistão', NULL, NULL);
INSERT INTO public.pais VALUES (246, 'Quitasueno', NULL, NULL);
INSERT INTO public.pais VALUES (247, 'República árabe do Egito', NULL, NULL);
INSERT INTO public.pais VALUES (248, 'República Centro Africana', NULL, NULL);
INSERT INTO public.pais VALUES (249, 'República da áfrica do Sul', NULL, NULL);
INSERT INTO public.pais VALUES (250, 'República da Bielorrússia', NULL, NULL);
INSERT INTO public.pais VALUES (251, 'República da Macedônia', NULL, NULL);
INSERT INTO public.pais VALUES (252, 'República de El Salvador', NULL, NULL);
INSERT INTO public.pais VALUES (253, 'República de Fiji', NULL, NULL);
INSERT INTO public.pais VALUES (254, 'República de Malta', NULL, NULL);
INSERT INTO public.pais VALUES (255, 'República do Gabão', NULL, NULL);
INSERT INTO public.pais VALUES (256, 'República do Haiti', NULL, NULL);
INSERT INTO public.pais VALUES (257, 'República do Níger', NULL, NULL);
INSERT INTO public.pais VALUES (259, 'República Guiana', NULL, NULL);
INSERT INTO public.pais VALUES (261, 'Reservado', NULL, NULL);
INSERT INTO public.pais VALUES (262, 'Reservado', NULL, NULL);
INSERT INTO public.pais VALUES (263, 'Reservado', NULL, NULL);
INSERT INTO public.pais VALUES (264, 'Reservado', NULL, NULL);
INSERT INTO public.pais VALUES (265, 'Reunião', NULL, NULL);
INSERT INTO public.pais VALUES (266, 'Rodésia (zimbábwe)', NULL, NULL);
INSERT INTO public.pais VALUES (267, 'Romênia', NULL, NULL);
INSERT INTO public.pais VALUES (268, 'Roncador', NULL, NULL);
INSERT INTO public.pais VALUES (270, 'Ruiquiu,is', NULL, NULL);
INSERT INTO public.pais VALUES (272, 'Saara Espanhol', NULL, NULL);
INSERT INTO public.pais VALUES (273, 'Sabah', NULL, NULL);
INSERT INTO public.pais VALUES (275, 'Samoa Ocidental', NULL, NULL);
INSERT INTO public.pais VALUES (279, 'São Cristóvão', NULL, NULL);
INSERT INTO public.pais VALUES (281, 'São Vicente', NULL, NULL);
INSERT INTO public.pais VALUES (282, 'Sarawak', NULL, NULL);
INSERT INTO public.pais VALUES (284, 'Sequin', NULL, NULL);
INSERT INTO public.pais VALUES (287, 'Seychelles', NULL, NULL);
INSERT INTO public.pais VALUES (289, 'Somália, República', NULL, NULL);
INSERT INTO public.pais VALUES (290, 'Sri-lanka', NULL, NULL);
INSERT INTO public.pais VALUES (291, 'St. Pierre et Miquelon', NULL, NULL);
INSERT INTO public.pais VALUES (297, 'Svalbard e Jan Mayer,is', NULL, NULL);
INSERT INTO public.pais VALUES (298, 'Tadjiquistão', NULL, NULL);
INSERT INTO public.pais VALUES (300, 'Tanganica', NULL, NULL);
INSERT INTO public.pais VALUES (302, 'Tartaria', NULL, NULL);
INSERT INTO public.pais VALUES (303, 'Tchecoslováquia', NULL, NULL);
INSERT INTO public.pais VALUES (304, 'Terr. Antártico da Austrália', NULL, NULL);
INSERT INTO public.pais VALUES (305, 'Terras Austrais', NULL, NULL);
INSERT INTO public.pais VALUES (306, 'Territ. Britânico do Oceano índico', NULL, NULL);
INSERT INTO public.pais VALUES (307, 'Território de Cocos', NULL, NULL);
INSERT INTO public.pais VALUES (308, 'Território de Papua', NULL, NULL);
INSERT INTO public.pais VALUES (309, 'Timor', NULL, NULL);
INSERT INTO public.pais VALUES (312, 'Transkei', NULL, NULL);
INSERT INTO public.pais VALUES (313, 'Trégua, Estado', NULL, NULL);
INSERT INTO public.pais VALUES (319, 'Tuvin', NULL, NULL);
INSERT INTO public.pais VALUES (321, 'Udmurt', NULL, NULL);
INSERT INTO public.pais VALUES (323, 'União Soviética', NULL, NULL);
INSERT INTO public.pais VALUES (327, 'Vietnã do Norte', NULL, NULL);
INSERT INTO public.pais VALUES (328, 'Vietnã do Sul', NULL, NULL);
INSERT INTO public.pais VALUES (329, 'Yakut', NULL, NULL);
INSERT INTO public.pais VALUES (330, 'Zaire', NULL, NULL);
INSERT INTO public.pais VALUES (332, 'Zimbábwe', NULL, NULL);
INSERT INTO public.pais VALUES (73, 'Costa Rica', NULL, 188);
INSERT INTO public.pais VALUES (76, 'Cuba', NULL, 192);
INSERT INTO public.pais VALUES (81, 'Dinamarca', NULL, 208);
INSERT INTO public.pais VALUES (258, 'República Dominicana', NULL, 214);
INSERT INTO public.pais VALUES (113, 'Guiné Equatorial', NULL, 226);
INSERT INTO public.pais VALUES (94, 'Etiópia', NULL, 231);
INSERT INTO public.pais VALUES (106, 'Grécia', NULL, 300);
INSERT INTO public.pais VALUES (118, 'Hungria', NULL, 348);
INSERT INTO public.pais VALUES (166, 'Indonésia', NULL, 360);
INSERT INTO public.pais VALUES (174, 'Itália', NULL, 380);
INSERT INTO public.pais VALUES (192, 'Libéria', NULL, 430);
INSERT INTO public.pais VALUES (195, 'Lituânia', NULL, 440);
INSERT INTO public.pais VALUES (200, 'Malásia', NULL, 458);
INSERT INTO public.pais VALUES (209, 'Mauritânia', NULL, 478);
INSERT INTO public.pais VALUES (210, 'México', NULL, 484);
INSERT INTO public.pais VALUES (214, 'Mônaco', NULL, 492);
INSERT INTO public.pais VALUES (4, 'Afeganistão', NULL, 4);
INSERT INTO public.pais VALUES (5, 'Albânia', NULL, 8);
INSERT INTO public.pais VALUES (19, 'Argélia', NULL, 12);
INSERT INTO public.pais VALUES (274, 'Samoa Americana', NULL, 16);
INSERT INTO public.pais VALUES (8, 'Andorra', NULL, 20);
INSERT INTO public.pais VALUES (9, 'Angola', NULL, 24);
INSERT INTO public.pais VALUES (20, 'Argentina', NULL, 32);
INSERT INTO public.pais VALUES (21, 'Armênia', NULL, 51);
INSERT INTO public.pais VALUES (25, 'Aruba', NULL, 533);
INSERT INTO public.pais VALUES (28, 'Austrália', NULL, 36);
INSERT INTO public.pais VALUES (29, 'áustria', NULL, 40);
INSERT INTO public.pais VALUES (30, 'Azerbaijão', NULL, 31);
INSERT INTO public.pais VALUES (31, 'Bahrein', NULL, 48);
INSERT INTO public.pais VALUES (32, 'Bangladesh', NULL, 50);
INSERT INTO public.pais VALUES (33, 'Barbados', NULL, 52);
INSERT INTO public.pais VALUES (36, 'Bélgica', NULL, 56);
INSERT INTO public.pais VALUES (37, 'Belize', NULL, 84);
INSERT INTO public.pais VALUES (39, 'Bermudas', NULL, 60);
INSERT INTO public.pais VALUES (42, 'Bolívia', NULL, 68);
INSERT INTO public.pais VALUES (45, 'Brasil', NULL, 76);
INSERT INTO public.pais VALUES (46, 'Brunei', NULL, 96);
INSERT INTO public.pais VALUES (47, 'Bulgária', NULL, 100);
INSERT INTO public.pais VALUES (49, 'Burundi', NULL, 108);
INSERT INTO public.pais VALUES (52, 'Camarões', NULL, 120);
INSERT INTO public.pais VALUES (53, 'Canadá', NULL, 124);
INSERT INTO public.pais VALUES (51, 'Cabo Verde', NULL, 132);
INSERT INTO public.pais VALUES (59, 'Chade', NULL, 148);
INSERT INTO public.pais VALUES (61, 'Chile', NULL, 152);
INSERT INTO public.pais VALUES (62, 'China', NULL, 156);
INSERT INTO public.pais VALUES (67, 'Colômbia', NULL, 170);
INSERT INTO public.pais VALUES (131, 'Ilhas Cook', NULL, 184);
INSERT INTO public.pais VALUES (72, 'Costa do Marfim', NULL, 384);
INSERT INTO public.pais VALUES (75, 'Croácia', NULL, 191);
INSERT INTO public.pais VALUES (64, 'Chipre', NULL, 196);
INSERT INTO public.pais VALUES (260, 'República Tcheca', NULL, 203);
INSERT INTO public.pais VALUES (85, 'Equador', NULL, 218);
INSERT INTO public.pais VALUES (145, 'Ilhas Malvinas', NULL, 238);
INSERT INTO public.pais VALUES (96, 'Finlândia', NULL, 246);
INSERT INTO public.pais VALUES (97, 'França', NULL, 250);
INSERT INTO public.pais VALUES (238, 'Polinésia Francesa', NULL, 258);
INSERT INTO public.pais VALUES (98, 'Gâmbia', NULL, 270);
INSERT INTO public.pais VALUES (101, 'Geórgia', NULL, 268);
INSERT INTO public.pais VALUES (99, 'Gana', NULL, 288);
INSERT INTO public.pais VALUES (107, 'Groenlândia', NULL, 304);
INSERT INTO public.pais VALUES (105, 'Granada', NULL, 308);
INSERT INTO public.pais VALUES (108, 'Guam', NULL, 316);
INSERT INTO public.pais VALUES (109, 'Guatemala', NULL, 320);
INSERT INTO public.pais VALUES (111, 'Guiné', NULL, 324);
INSERT INTO public.pais VALUES (115, 'Honduras', NULL, 340);
INSERT INTO public.pais VALUES (172, 'Islândia', NULL, 352);
INSERT INTO public.pais VALUES (168, 'Irã', NULL, 364);
INSERT INTO public.pais VALUES (169, 'Iraque', NULL, 368);
INSERT INTO public.pais VALUES (170, 'Irlanda', NULL, 372);
INSERT INTO public.pais VALUES (173, 'Israel', NULL, 376);
INSERT INTO public.pais VALUES (176, 'Jamaica', NULL, 388);
INSERT INTO public.pais VALUES (177, 'Japão', NULL, 392);
INSERT INTO public.pais VALUES (178, 'Jordânia', NULL, 400);
INSERT INTO public.pais VALUES (56, 'Cazaquistão', NULL, 398);
INSERT INTO public.pais VALUES (188, 'Laos', NULL, 418);
INSERT INTO public.pais VALUES (191, 'Líbano', NULL, 422);
INSERT INTO public.pais VALUES (189, 'Lesoto', NULL, 426);
INSERT INTO public.pais VALUES (193, 'Líbia', NULL, 434);
INSERT INTO public.pais VALUES (194, 'Liechtenstein', NULL, 438);
INSERT INTO public.pais VALUES (196, 'Luxemburgo', NULL, 442);
INSERT INTO public.pais VALUES (197, 'Macau', NULL, 446);
INSERT INTO public.pais VALUES (201, 'Malawi', NULL, 454);
INSERT INTO public.pais VALUES (203, 'Mali', NULL, 466);
INSERT INTO public.pais VALUES (147, 'Ilhas Marshall', NULL, 584);
INSERT INTO public.pais VALUES (206, 'Martinica', NULL, 474);
INSERT INTO public.pais VALUES (213, 'Moldávia', NULL, 498);
INSERT INTO public.pais VALUES (215, 'Mongólia', NULL, 496);
INSERT INTO public.pais VALUES (217, 'Montenegro', NULL, 499);
INSERT INTO public.pais VALUES (205, 'Marrocos', NULL, 504);
INSERT INTO public.pais VALUES (212, 'Moçambique', NULL, 508);
INSERT INTO public.pais VALUES (218, 'Namíbia', NULL, 516);
INSERT INTO public.pais VALUES (219, 'Nauru', NULL, 520);
INSERT INTO public.pais VALUES (220, 'Nepal', NULL, 524);
INSERT INTO public.pais VALUES (114, 'Holanda', NULL, 528);
INSERT INTO public.pais VALUES (296, 'Suriname', NULL, 740);
INSERT INTO public.pais VALUES (16, 'Antilhas Holandesas', NULL, 530);
INSERT INTO public.pais VALUES (226, 'Nova Zelândia', NULL, 554);
INSERT INTO public.pais VALUES (222, 'Nicarágua', NULL, 558);
INSERT INTO public.pais VALUES (223, 'Nigéria', NULL, 566);
INSERT INTO public.pais VALUES (224, 'Noruega', NULL, 578);
INSERT INTO public.pais VALUES (235, 'Paquistão', NULL, 586);
INSERT INTO public.pais VALUES (231, 'Palestina', NULL, 275);
INSERT INTO public.pais VALUES (232, 'Panamá', NULL, 591);
INSERT INTO public.pais VALUES (236, 'Paraguai', NULL, 600);
INSERT INTO public.pais VALUES (237, 'Peru', NULL, 604);
INSERT INTO public.pais VALUES (95, 'Filipinas', NULL, 608);
INSERT INTO public.pais VALUES (239, 'Polônia', NULL, 616);
INSERT INTO public.pais VALUES (241, 'Portugal', NULL, 620);
INSERT INTO public.pais VALUES (240, 'Porto Rico', NULL, 630);
INSERT INTO public.pais VALUES (55, 'Catar', NULL, 634);
INSERT INTO public.pais VALUES (271, 'Rússia', NULL, 643);
INSERT INTO public.pais VALUES (277, 'Santa Helena', NULL, 654);
INSERT INTO public.pais VALUES (278, 'Santa Lúcia', NULL, 662);
INSERT INTO public.pais VALUES (276, 'San Marino', NULL, 674);
INSERT INTO public.pais VALUES (18, 'Arábia Saudita', NULL, 682);
INSERT INTO public.pais VALUES (283, 'Senegal', NULL, 686);
INSERT INTO public.pais VALUES (286, 'Sérvia', NULL, 688);
INSERT INTO public.pais VALUES (285, 'Serra Leoa', NULL, 694);
INSERT INTO public.pais VALUES (66, 'Cingapura', NULL, 702);
INSERT INTO public.pais VALUES (87, 'Eslováquia', NULL, 703);
INSERT INTO public.pais VALUES (88, 'Eslovênia', NULL, 705);
INSERT INTO public.pais VALUES (155, 'Ilhas Salomão', NULL, 90);
INSERT INTO public.pais VALUES (292, 'Suazilândia', NULL, 748);
INSERT INTO public.pais VALUES (294, 'Suécia', NULL, 752);
INSERT INTO public.pais VALUES (295, 'Suíça', NULL, 756);
INSERT INTO public.pais VALUES (288, 'Síria', NULL, 760);
INSERT INTO public.pais VALUES (299, 'Tailândia', NULL, 764);
INSERT INTO public.pais VALUES (310, 'Togo', NULL, 768);
INSERT INTO public.pais VALUES (311, 'Tonga', NULL, 776);
INSERT INTO public.pais VALUES (314, 'Trinidad e Tobago', NULL, 780);
INSERT INTO public.pais VALUES (315, 'Tunísia', NULL, 788);
INSERT INTO public.pais VALUES (317, 'Turquia', NULL, 792);
INSERT INTO public.pais VALUES (318, 'Tuvalu', NULL, 798);
INSERT INTO public.pais VALUES (322, 'Uganda', NULL, 800);
INSERT INTO public.pais VALUES (320, 'Ucrânia', NULL, 804);
INSERT INTO public.pais VALUES (84, 'Emirados árabes Unidos', NULL, 784);
INSERT INTO public.pais VALUES (92, 'Estados Unidos da América (eua)', NULL, 840);
INSERT INTO public.pais VALUES (324, 'Uruguai', NULL, 858);
INSERT INTO public.pais VALUES (325, 'Uzbequistão', NULL, 860);
INSERT INTO public.pais VALUES (326, 'Venezuela', NULL, 862);
INSERT INTO public.pais VALUES (162, 'Ilhas Virgens Britânicas', NULL, 92);
INSERT INTO public.pais VALUES (161, 'Ilhas Virgens Americanas', NULL, 850);
INSERT INTO public.pais VALUES (331, 'Zâmbia', NULL, 894);
INSERT INTO public.pais VALUES (93, 'Estônia', NULL, 233);
INSERT INTO public.pais VALUES (102, 'Gibraltar', NULL, 292);
INSERT INTO public.pais VALUES (269, 'Ruanda', NULL, 646);
INSERT INTO public.pais VALUES (280, 'São Tomé e Príncipe', NULL, 678);
INSERT INTO public.pais VALUES (89, 'Espanha', NULL, 724);
INSERT INTO public.pais VALUES (301, 'Tanzânia', NULL, 834);
INSERT INTO public.pais VALUES (316, 'Turcomenistão', NULL, 795);
INSERT INTO public.pais VALUES (6, 'Alemanha', NULL, 276);
INSERT INTO public.pais VALUES (17, 'Apátrida', NULL, 339);
INSERT INTO public.pais VALUES (77, 'Curaçao', NULL, 531);
INSERT INTO public.pais VALUES (293, 'Sudão', NULL, 729);
INSERT INTO public.pais VALUES (134, 'Ilhas do Canal', NULL, 830);
