INSERT INTO urbano.tipo_logradouro VALUES ('CORRE', 'Corredor');
INSERT INTO urbano.tipo_logradouro VALUES ('DESCI', 'Descida');
INSERT INTO urbano.tipo_logradouro VALUES ('AEROP', 'Aeroporto');
INSERT INTO urbano.tipo_logradouro VALUES ('DESVI', 'Desvio');
INSERT INTO urbano.tipo_logradouro VALUES ('ELEVA', 'Elevada');
INSERT INTO urbano.tipo_logradouro VALUES ('ENTRP', 'Entrada Particular');
INSERT INTO urbano.tipo_logradouro VALUES ('ESCA', 'Escada');
INSERT INTO urbano.tipo_logradouro VALUES ('ESCAD', 'Escadaria');
INSERT INTO urbano.tipo_logradouro VALUES ('ESTAC', 'Estacionamento');
INSERT INTO urbano.tipo_logradouro VALUES ('ESPLA', 'Esplanada');
INSERT INTO urbano.tipo_logradouro VALUES ('GALER', 'Galeria');
INSERT INTO urbano.tipo_logradouro VALUES ('ILHA', 'Ilha');
INSERT INTO urbano.tipo_logradouro VALUES ('JDNET', 'Jardinete');
INSERT INTO urbano.tipo_logradouro VALUES ('LAGO', 'Lago');
INSERT INTO urbano.tipo_logradouro VALUES ('LAGOA', 'Lagoa');
INSERT INTO urbano.tipo_logradouro VALUES ('MONTE', 'Monte');
INSERT INTO urbano.tipo_logradouro VALUES ('MARIN', 'Marina');
INSERT INTO urbano.tipo_logradouro VALUES ('VERED', 'Vereda');
INSERT INTO urbano.tipo_logradouro VALUES ('CORRG', 'Córrego');
INSERT INTO urbano.tipo_logradouro VALUES ('PASSE', 'Passeio');
INSERT INTO urbano.tipo_logradouro VALUES ('BULEV', 'Bulevar');
INSERT INTO urbano.tipo_logradouro VALUES ('COLON', 'Colônia');
INSERT INTO urbano.tipo_logradouro VALUES ('PATIO', 'Pátio');
INSERT INTO urbano.tipo_logradouro VALUES ('TUNEL', 'Túnel');
INSERT INTO urbano.tipo_logradouro VALUES ('ROTUL', 'Rótula');
INSERT INTO urbano.tipo_logradouro VALUES ('ESTAD', 'Estádio');
INSERT INTO urbano.tipo_logradouro VALUES ('MODUL', 'Módulo');
INSERT INTO urbano.tipo_logradouro VALUES ('SERVI', 'Servidão');
INSERT INTO urbano.tipo_logradouro VALUES ('ALM', 'Alameda');
INSERT INTO urbano.tipo_logradouro VALUES ('ALTO', 'Alto');
INSERT INTO urbano.tipo_logradouro VALUES ('AV', 'Avenida');
INSERT INTO urbano.tipo_logradouro VALUES ('BEC', 'Beco');
INSERT INTO urbano.tipo_logradouro VALUES ('COND', 'Condomínio');
INSERT INTO urbano.tipo_logradouro VALUES ('CONJ', 'Conjunto');
INSERT INTO urbano.tipo_logradouro VALUES ('DIV', 'Divisa');
INSERT INTO urbano.tipo_logradouro VALUES ('EST', 'Estrada');
INSERT INTO urbano.tipo_logradouro VALUES ('FEIRA', 'Feira');
INSERT INTO urbano.tipo_logradouro VALUES ('JD', 'Jardim');
INSERT INTO urbano.tipo_logradouro VALUES ('LAD', 'Ladeira');
INSERT INTO urbano.tipo_logradouro VALUES ('LTM', 'Loteamento');
INSERT INTO urbano.tipo_logradouro VALUES ('LRG', 'Largo');
INSERT INTO urbano.tipo_logradouro VALUES ('MRG', 'Margem');
INSERT INTO urbano.tipo_logradouro VALUES ('PORTO', 'Porto');
INSERT INTO urbano.tipo_logradouro VALUES ('PQE', 'Parque');
INSERT INTO urbano.tipo_logradouro VALUES ('PRAIA', 'Praia');
INSERT INTO urbano.tipo_logradouro VALUES ('QDA', 'Quadra');
INSERT INTO urbano.tipo_logradouro VALUES ('REC', 'Recanto');
INSERT INTO urbano.tipo_logradouro VALUES ('RES', 'Residencial');
INSERT INTO urbano.tipo_logradouro VALUES ('RET', 'Retorno');
INSERT INTO urbano.tipo_logradouro VALUES ('ROD', 'Rodovia');
INSERT INTO urbano.tipo_logradouro VALUES ('ROT', 'Rotatória');
INSERT INTO urbano.tipo_logradouro VALUES ('RUA', 'Rua');
INSERT INTO urbano.tipo_logradouro VALUES ('TER', 'Terminal');
INSERT INTO urbano.tipo_logradouro VALUES ('TRV', 'Travessa');
INSERT INTO urbano.tipo_logradouro VALUES ('UND', 'Unidade');
INSERT INTO urbano.tipo_logradouro VALUES ('VIA', 'Via');
INSERT INTO urbano.tipo_logradouro VALUES ('VLA', 'Vila');
INSERT INTO urbano.tipo_logradouro VALUES ('ACAMP', 'Acampamento');
INSERT INTO urbano.tipo_logradouro VALUES ('ACESS', 'Acesso');
INSERT INTO urbano.tipo_logradouro VALUES ('VIACE', 'Via de Acesso');
INSERT INTO urbano.tipo_logradouro VALUES ('ADRO', 'Adro');
INSERT INTO urbano.tipo_logradouro VALUES ('ANTES', 'Antiga Estrada');
INSERT INTO urbano.tipo_logradouro VALUES ('AREA', 'Área');
INSERT INTO urbano.tipo_logradouro VALUES ('ARESP', 'Área Especial');
INSERT INTO urbano.tipo_logradouro VALUES ('ATALH', 'Atalho');
INSERT INTO urbano.tipo_logradouro VALUES ('AVCON', 'Avenida Contorno');
INSERT INTO urbano.tipo_logradouro VALUES ('AVMAR', 'Avenida Marginal');
INSERT INTO urbano.tipo_logradouro VALUES ('AVVEL', 'Avenida Velha');
INSERT INTO urbano.tipo_logradouro VALUES ('PARAL', 'Paralela');
INSERT INTO urbano.tipo_logradouro VALUES ('ENTRQ', 'Entre Quadra');
INSERT INTO urbano.tipo_logradouro VALUES ('PRQMU', 'Parque Municipal');
INSERT INTO urbano.tipo_logradouro VALUES ('PRQRE', 'Parque Residencial');
INSERT INTO urbano.tipo_logradouro VALUES ('BAIXA', 'Baixa');
INSERT INTO urbano.tipo_logradouro VALUES ('PASSG', 'Passagem');
INSERT INTO urbano.tipo_logradouro VALUES ('PASPE', 'Passagem de Pedestres');
INSERT INTO urbano.tipo_logradouro VALUES ('PASSB', 'Passagem Subterrânea');
INSERT INTO urbano.tipo_logradouro VALUES ('BELVE', 'Belvedere');
INSERT INTO urbano.tipo_logradouro VALUES ('PASSA', 'Passarela');
INSERT INTO urbano.tipo_logradouro VALUES ('BLOCO', 'Bloco');
INSERT INTO urbano.tipo_logradouro VALUES ('BOSQU', 'Bosque');
INSERT INTO urbano.tipo_logradouro VALUES ('PONTA', 'Ponta');
INSERT INTO urbano.tipo_logradouro VALUES ('BOULE', 'Boulevard');
INSERT INTO urbano.tipo_logradouro VALUES ('ZIGUE', 'Zigue-Zague');
INSERT INTO urbano.tipo_logradouro VALUES ('VIELA', 'Viela');
INSERT INTO urbano.tipo_logradouro VALUES ('VIDUT', 'Viaduto');
INSERT INTO urbano.tipo_logradouro VALUES ('VIALO', 'Via Local');
INSERT INTO urbano.tipo_logradouro VALUES ('VIAPE', 'Via de Pedestre');
INSERT INTO urbano.tipo_logradouro VALUES ('VIALI', 'Via Litorânea');
INSERT INTO urbano.tipo_logradouro VALUES ('VIAEL', 'Via Elevado');
INSERT INTO urbano.tipo_logradouro VALUES ('VIAEX', 'Via Expressa');
INSERT INTO urbano.tipo_logradouro VALUES ('VIACO', 'Via Coletora');
INSERT INTO urbano.tipo_logradouro VALUES ('CAMIN', 'Caminho');
INSERT INTO urbano.tipo_logradouro VALUES ('VALE', 'Vale');
INSERT INTO urbano.tipo_logradouro VALUES ('VALA', 'Vala');
INSERT INTO urbano.tipo_logradouro VALUES ('TRAVP', 'Travessa Particular');
INSERT INTO urbano.tipo_logradouro VALUES ('TRAVV', 'Travessa Velha');
INSERT INTO urbano.tipo_logradouro VALUES ('TRECH', 'Trecho');
INSERT INTO urbano.tipo_logradouro VALUES ('TREVO', 'Trevo');
INSERT INTO urbano.tipo_logradouro VALUES ('RUAPE', 'Rua de Pedestre');
INSERT INTO urbano.tipo_logradouro VALUES ('RUAPA', 'Rua Particular');
INSERT INTO urbano.tipo_logradouro VALUES ('RUAVE', 'Rua Velha');
INSERT INTO urbano.tipo_logradouro VALUES ('SUBID', 'Subida');
INSERT INTO urbano.tipo_logradouro VALUES ('PONTE', 'Ponte');
INSERT INTO urbano.tipo_logradouro VALUES ('RAMPA', 'Rampa');
INSERT INTO urbano.tipo_logradouro VALUES ('BURAC', 'Buraco');
INSERT INTO urbano.tipo_logradouro VALUES ('QUINT', 'Quinta');
INSERT INTO urbano.tipo_logradouro VALUES ('RETIR', 'Retiro');
INSERT INTO urbano.tipo_logradouro VALUES ('CAIS', 'Cais');
INSERT INTO urbano.tipo_logradouro VALUES ('FONTE', 'Fonte');
INSERT INTO urbano.tipo_logradouro VALUES ('PROLO', 'Prolongamento');
INSERT INTO urbano.tipo_logradouro VALUES ('PARAD', 'Parada');
INSERT INTO urbano.tipo_logradouro VALUES ('SETOR', 'Setor');
INSERT INTO urbano.tipo_logradouro VALUES ('RETA', 'Reta');
INSERT INTO urbano.tipo_logradouro VALUES ('MORRO', 'Morro');
INSERT INTO urbano.tipo_logradouro VALUES ('RODAN', 'Rodo Anel');
INSERT INTO urbano.tipo_logradouro VALUES ('RAMAL', 'Ramal');
INSERT INTO urbano.tipo_logradouro VALUES ('FERRO', 'Ferrovia');
INSERT INTO urbano.tipo_logradouro VALUES ('CANAL', 'Canal');
INSERT INTO urbano.tipo_logradouro VALUES ('FORT', 'Forte');
INSERT INTO urbano.tipo_logradouro VALUES ('DISTR', 'Distrito');
INSERT INTO urbano.tipo_logradouro VALUES ('ESTRE', 'Estrada Estadual');
INSERT INTO urbano.tipo_logradouro VALUES ('ESTRM', 'Estrada Municipal');
INSERT INTO urbano.tipo_logradouro VALUES ('ESTRP', 'Estrada Particular');
INSERT INTO urbano.tipo_logradouro VALUES ('ESTRV', 'Estrada Velha');
INSERT INTO urbano.tipo_logradouro VALUES ('ESTRC', 'Estrada Vicinal');
INSERT INTO urbano.tipo_logradouro VALUES ('CICLO', 'Ciclovia');
INSERT INTO urbano.tipo_logradouro VALUES ('GRANJ', 'Granja');
INSERT INTO urbano.tipo_logradouro VALUES ('FAZEN', 'Fazenda');
INSERT INTO urbano.tipo_logradouro VALUES ('CAMPO', 'Campo');
INSERT INTO urbano.tipo_logradouro VALUES ('FAVEL', 'Favela');
INSERT INTO urbano.tipo_logradouro VALUES ('CIRCU', 'Circular');
INSERT INTO urbano.tipo_logradouro VALUES ('CONTO', 'Contorno');
INSERT INTO urbano.tipo_logradouro VALUES ('RUALI', 'Rua de Ligação');
INSERT INTO urbano.tipo_logradouro VALUES ('ROTAT', 'Rotatória');
INSERT INTO urbano.tipo_logradouro VALUES ('NUCLE', 'Núcleo');
INSERT INTO urbano.tipo_logradouro VALUES ('ESTRL', 'Estrada de Ligação');
INSERT INTO urbano.tipo_logradouro VALUES ('ARTER', 'Artéria');
INSERT INTO urbano.tipo_logradouro VALUES ('COMVI', 'Complexo Viário');
INSERT INTO urbano.tipo_logradouro VALUES ('CJOMU', 'Conjunto Mutirão');
INSERT INTO urbano.tipo_logradouro VALUES ('BALAO', 'Balão');
INSERT INTO urbano.tipo_logradouro VALUES ('CALCA', 'Calçada');
INSERT INTO urbano.tipo_logradouro VALUES ('CHAC', 'Chácara');
INSERT INTO urbano.tipo_logradouro VALUES ('ESTAO', 'Estação');
INSERT INTO urbano.tipo_logradouro VALUES ('PCA', 'Praça');
INSERT INTO urbano.tipo_logradouro VALUES ('PCAES', 'Praça Esportes');
INSERT INTO urbano.tipo_logradouro VALUES ('SITIO', 'Sítio');
INSERT INTO urbano.tipo_logradouro VALUES ('ASSEN', 'Assentamento');
INSERT INTO urbano.tipo_logradouro VALUES ('POVO', 'Povoado');
INSERT INTO urbano.tipo_logradouro VALUES ('LOCAL', 'Localidade');
