<?php

namespace App;

class Process
{
    const MENU_ADDRESSING = 68;
    const MENU_PEOPLE = 7;
    const MENU_SCHOOL = 55;
    const MENU_EMPLOYEES = 71;
    const MENU_EDUCACENSO = 70;
    const MENU_TRANSPORT = 69;
    const MENU_LIBRARY = 57;
    const MENU_CONFIGURATIONS = 25;

    const CONSULTAS = 9998890;

    const MENU_SCHOOL_TOOLS = 999926;
    const EDUCACENSO_IMPORTACOES = 9998848;

    const CONFIGURATIONS_TOOLS = 999910;

    const REGISTRATIONS = 578;
    const ENROLLMENT_HISTORY = 1001;
    const ATTENDED_CANDIDATE = 1002;
    const BACK_TO_QUEUE = 1003;
    const RECLASSIFY_REGISTRATION = 1004;
    const UNDO_STUDENT_UNIFICATION = 2001;
    const EXEMPTION_LIST = 2002;
    const ALLOW_VACANCY_RESERVATION_REPORT_WITHOUT_SCHOOL = 2003;
    const EDUCACENSO_IMPORT_HISTORY = 2004;
    const UPDATE_REGISTRATION_STATUS = 2005;
    const MENU_SCHOOL_TOOLS_EXPORTS = 1020;
    const SEB_EXPORT = 1021;
}
