<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

class UpdateCollegeNameEducacenso extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        DB::unprepared("
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSITARIO MUNICIPAL DE FRANCA' WHERE ies_id = 60;
            UPDATE modules.educacenso_ies SET nome = 'UNIVERSIDADE ESTADUAL VALE DO ACARAU' WHERE ies_id = 95;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE DE FILOSOFIA CIENCIAS E LETRAS DE ARAGUARI' WHERE ies_id = 103;
            UPDATE modules.educacenso_ies SET nome = 'UNIVERSIDADE DE ARARAQUARA' WHERE ies_id = 124;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSITARIO DE ARARAS' WHERE ies_id = 125;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSITARIO SAGRADO CORACAO' WHERE ies_id = 137;
            UPDATE modules.educacenso_ies SET nome = 'UNIVERSIDADE DE VASSOURAS' WHERE ies_id = 140;
            UPDATE modules.educacenso_ies SET nome = 'CONSERVATORIO BRASILEIRO DE MUSICA CENTRO UNIVERSITARIO BRASILEIRO DE EDUCACAO' WHERE ies_id = 158;
            UPDATE modules.educacenso_ies SET nome = 'FAI CENTRO DE ENSINO SUPERIOR EM GESTAO TECNOLOGIA E EDUCACAO' WHERE ies_id = 166;
            UPDATE modules.educacenso_ies SET nome = 'FUNVIC FACULDADE FUNVIC DE MOCOCA' WHERE ies_id = 170;
            UPDATE modules.educacenso_ies SET nome = 'ESCOLA DE MEDICINA SOUZA MARQUES DA FUNDACAO TECNICOEDUCACIONAL SOUZA MARQUES' WHERE ies_id = 190;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE PRESBITERIANA MACKENZIE RIO' WHERE ies_id = 195;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE DO RIO DE JANEIRO' WHERE ies_id = 202;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE DE CIENCIAS ECONOMICAS E ADMINISTR1S DE SANTO ANDRE' WHERE ies_id = 211;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSITARIO ALVARES PENTEADO' WHERE ies_id = 213;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE DE FILOSOFIA CIENCIAS E LETRAS DE DUQUE DE CAXIAS' WHERE ies_id = 218;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSITARIO SAUDE ABC' WHERE ies_id = 224;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE DE SANTO ANDRE' WHERE ies_id = 225;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE DE CIENCIAS CONTABEIS E ADMINISTR1S DE SAO JOAO DA BOA VISTA' WHERE ies_id = 236;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSITARIO ANHANGUERA DE SANTO ANDRE' WHERE ies_id = 242;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSITARIO UNIBAN' WHERE ies_id = 254;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE DE PIRAJU' WHERE ies_id = 256;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSITARIO DAS FACULDADES INTEGRADAS DE OURINHOS' WHERE ies_id = 265;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSITARIO ESPIRITOSANTENSE/FAESA' WHERE ies_id = 267;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE DE TUPA' WHERE ies_id = 270;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE DE CIENCIAS ADMINISTR1S E CONTABEIS COSTA BRAGA' WHERE ies_id = 282;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSITARIO DA REGIAO DA CAMPANHA' WHERE ies_id = 296;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE DE CIENCIAS CONTABEIS E ADMINISTR1S SAO JUDAS TADEU' WHERE ies_id = 297;
            UPDATE modules.educacenso_ies SET nome = 'UNIVERSIDADE PITAGORAS UNOPAR' WHERE ies_id = 298;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE DE FILOSOFIA CIENCIAS E LETRAS DE FORMIGA' WHERE ies_id = 300;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE DIVINOPOLIS' WHERE ies_id = 302;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE DE FILOSOFIA CIENCIAS E LETRAS DE CATAGUASES' WHERE ies_id = 303;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSITARIO PRESIDENTE ANTONIO CARLOS' WHERE ies_id = 308;
            UPDATE modules.educacenso_ies SET nome = 'UNIVERSIDADE BRASIL' WHERE ies_id = 319;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE UNIDAS DE TATUI' WHERE ies_id = 321;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE DE JOAO PESSOA (SANTA EMILIA DO RODAT)' WHERE ies_id = 339;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE EVANGELICA MACKENZIE DO PARANA' WHERE ies_id = 353;
            UPDATE modules.educacenso_ies SET nome = 'UNIVERSIDADE SANTO AMARO' WHERE ies_id = 375;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE DE CIENCIAS ECONOMICAS CONTABEIS E DE ADM DE EMPRESAS PADRE ANCHIETA' WHERE ies_id = 380;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSITARIO RUY BARBOSA WYDEN' WHERE ies_id = 396;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE PORTOALEGRENSE DE EDUCACAO CIENCIAS E LETRAS' WHERE ies_id = 413;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE PORTOALEGRENSE DE CIENCIAS CONTABEIS E ADMINISTR1S' WHERE ies_id = 414;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE DE CIENCIAS CONTABEIS E ADMINISTR1S DE SANTA ROSA' WHERE ies_id = 424;
            UPDATE modules.educacenso_ies SET nome = 'UNIVERSIDADE FRANCISCANA' WHERE ies_id = 426;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE SANTA MARCELINA MURIAE FASM' WHERE ies_id = 435;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE DE CIENCIAS CONTABEIS E ADMINISTR1S DE ITARARE' WHERE ies_id = 443;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSITARIO SAO LUCAS JIPARANA' WHERE ies_id = 450;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSITARIO SANT¿ANNA' WHERE ies_id = 456;
            UPDATE modules.educacenso_ies SET nome = 'UNIVERSIDADE ANHANGUERA DE SAO PAULO' WHERE ies_id = 457;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE ARMANDO ALVARES PENTEADO' WHERE ies_id = 461;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE DE FILOSOFIA CIENCIAS E LETRAS DE ITAPETININGA' WHERE ies_id = 468;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE DE CIENCIAS ECONOMICAS ADMINISTRATIVAS E DA COMPUTACAO DOM BOSCO' WHERE ies_id = 473;
            UPDATE modules.educacenso_ies SET nome = 'UNIVERSIDADE UNIVERSUS VERITAS GUARULHOS' WHERE ies_id = 481;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE DE ADMINISTRACAO CIENCIAS CONTABEIS JURIDICAS E SOCIAIS DO ESTADO DE ALAGOAS' WHERE ies_id = 487;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSITARIO DE VALENCA' WHERE ies_id = 490;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSITARIO DON DOMENICO' WHERE ies_id = 491;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSITARIO SAO JUDAS TADEU' WHERE ies_id = 502;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE MAIS DE ITUIUTABA' WHERE ies_id = 507;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE DE CIENCIAS SOCIAIS APLICADAS DO SUL DE MINAS FACESM' WHERE ies_id = 508;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE WENCESLAU BRAZ' WHERE ies_id = 510;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE DE FILOSOFIA CIENCIAS E LETRAS DE GUAXUPE' WHERE ies_id = 511;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE DE CIENCIAS ADMINISTR1S ECONOMICAS E CONTABEIS DE GUAXUPE' WHERE ies_id = 512;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSITARIO DO RIO DE JANEIRO' WHERE ies_id = 516;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSITARIO BRAZ CUBAS' WHERE ies_id = 526;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSITARIO CENECISTA DE OSORIO' WHERE ies_id = 626;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE DE DESENVOLVIMENTO DAS CIENCIAS E HUMANIDADES' WHERE ies_id = 545;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE DE CIENCIAS ADMINISTR1S DE CARATINGA' WHERE ies_id = 553;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE DE FILOSOFIA CIENCIAS E LETRAS DE BOA ESPERANCA' WHERE ies_id = 554;
            UPDATE modules.educacenso_ies SET nome = 'INSTITUTO FEDERAL DE EDUCACAO CIENCIA E TECNOLOGIA DA BAHIA' WHERE ies_id = 599;
            UPDATE modules.educacenso_ies SET nome = 'INSTITUTO FEDERAL DE EDUCACAO CIENCIA E TECNOLOGIA DO MARANHAO' WHERE ies_id = 600;
            UPDATE modules.educacenso_ies SET nome = 'INSTITUTO FEDERAL DE EDUCACAO CIENCIA E TECNOLOGIA DO RIO GRANDE DO SUL' WHERE ies_id = 601;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSITARIO UNIVERSUS VERITAS' WHERE ies_id = 610;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE DE FILOSOFIA CIENCIAS E LETRAS PROFESSORA NAIR FORTES ABUMERHY' WHERE ies_id = 615;
            UPDATE modules.educacenso_ies SET nome = 'ICEV INSTITUTO DE ENSINO SUPERIOR' WHERE ies_id = 1360;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE CNEC VARGINHA' WHERE ies_id = 627;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE CENECISTA DE CIENCIAS ADMINISTR1S DE OSORIO' WHERE ies_id = 630;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE CNEC FARROUPILHA' WHERE ies_id = 631;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE DE CIENCIAS ECONOMICAS ADMINISTR1S E CONTABEIS DE SAO SEBASTIAO DO PARAISO' WHERE ies_id = 632;
            UPDATE modules.educacenso_ies SET nome = 'UNIVERSIDADE LA SALLE' WHERE ies_id = 641;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSITARIO CATOLICA DE SANTA CATARINA EM JARAGUA DO SUL' WHERE ies_id = 645;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE DE AVARE' WHERE ies_id = 650;
            UPDATE modules.educacenso_ies SET nome = 'UNIVERSIDADE ANHANGUERA' WHERE ies_id = 671;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSITARIO FACENS' WHERE ies_id = 672;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADES REUNIDAS DA ASCE' WHERE ies_id = 677;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE DO BELO JARDIM' WHERE ies_id = 685;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE DE CIENCIAS CONTABEIS E ADMINISTR1S DE TAQUARA' WHERE ies_id = 690;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADES INTEGRADAS DE GARANHUNS' WHERE ies_id = 701;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE DE CIENCIAS E TECNOLOGIA PROFESSOR DIRSON MACIEL DE BARROS' WHERE ies_id = 702;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSITARIO SAO JOSE' WHERE ies_id = 705;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSITARIO IBMR' WHERE ies_id = 712;
            UPDATE modules.educacenso_ies SET nome = 'UNIVERSIDADE DO ESTADO DE MATO GROSSO CARLOS ALBERTO REYES MALDONADO UNEMAT' WHERE ies_id = 719;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE ESTADUAL DE FILOSOFIA CIENCIAS E LETRAS DE PARANAGUA' WHERE ies_id = 725;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE DE FILOSOFIA CIENCIAS E LETRAS DO ALTO SAO FRANCISCO' WHERE ies_id = 727;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSITARIO TERESA D AVILA' WHERE ies_id = 738;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE DE ANICUNS' WHERE ies_id = 744;
            UPDATE modules.educacenso_ies SET nome = 'UNIVERSIDADE DE GURUPI' WHERE ies_id = 750;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO SUPERIOR UNA DE CATALAO' WHERE ies_id = 754;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSITARIO DA AMAZONIA' WHERE ies_id = 757;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE NACIONAL DE CURITIBA' WHERE ies_id = 761;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE DE RONDONOPOLIS' WHERE ies_id = 781;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE MATOGROSSENSE DE CIENCIAS CONTABEIS E ADMINISTR1 DE CUIABA' WHERE ies_id = 783;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE ISRAELITA DE CIENCIAS DA SAUDE ALBERT EINSTEIN' WHERE ies_id = 790;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSITARIO ESTACIO DE SAO PAULO' WHERE ies_id = 793;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSITARIO UNICARIOCA' WHERE ies_id = 802;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO TECNICOEDUCACIONAL SUPERIOR DO OESTE PARANAENSE' WHERE ies_id = 810;
            UPDATE modules.educacenso_ies SET nome = 'UNIVERSIDADE CEUMA' WHERE ies_id = 823;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSITARIO DE GOIATUBA' WHERE ies_id = 824;
            UPDATE modules.educacenso_ies SET nome = 'UNIVERSIDADE ESTADUAL DO TOCANTINS' WHERE ies_id = 829;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSITARIO CATOLICA DO LESTE DE MINAS GERAIS' WHERE ies_id = 878;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE PITAGORAS' WHERE ies_id = 891;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSITARIO SANTA RITA' WHERE ies_id = 898;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE DE SUMARE' WHERE ies_id = 906;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE FERNANDA BICCHIERI' WHERE ies_id = 909;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE ESTACIO DE TERESINA' WHERE ies_id = 916;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSITARIO UNIVEL' WHERE ies_id = 918;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSITARIO SAO ROQUE' WHERE ies_id = 923;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE FUNORTE DE JANUARIA' WHERE ies_id = 945;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE EVANGELICA DE RUBIATABA' WHERE ies_id = 985;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE DE CIENCIAS ECONOMICAS E ADMINISTR1S DE PRESIDENTE PRUDENTE' WHERE ies_id = 1001;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE DO SERTAO DO PAJEU' WHERE ies_id = 1012;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSITARIO IBMEC' WHERE ies_id = 1030;
            UPDATE modules.educacenso_ies SET nome = 'UNIVERSIDADE DO VALE DO TAQUARI' WHERE ies_id = 1041;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSITARIO DA FUNDACAO HERMINIO OMETTO' WHERE ies_id = 1043;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE DA SEUNE' WHERE ies_id = 1051;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSIARIO UNIFTC DE FEIRA DE SANTANA' WHERE ies_id = 1053;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSITARIO MAURICIO DE NASSAU DE SALVADOR' WHERE ies_id = 1055;
            UPDATE modules.educacenso_ies SET nome = 'ESTACIO FIB CENTRO UNIVERSITARIO ESTACIO DA BAHIA' WHERE ies_id = 1058;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE DOCTUM DE VILA VELHA' WHERE ies_id = 1063;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE DOCTUM DE VITORIA' WHERE ies_id = 1064;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE DE CIENCIAS ECONOMICAS E ADMINISTR1S DE VILA VELHA' WHERE ies_id = 1065;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE CNEC UNAI' WHERE ies_id = 1070;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSITARIO UNIESP' WHERE ies_id = 1075;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE DE FILOSOFIA CIENCIAS E LETRAS DE CAJAZEIRAS' WHERE ies_id = 1076;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSITARIO ESTACIO DO RECIFE' WHERE ies_id = 1077;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSITARIO INTEGRADO DE CAMPO MOURAO' WHERE ies_id = 1078;
            UPDATE modules.educacenso_ies SET nome = 'INSTITUTO FEDERAL DE EDUCACAO CIENCIA E TECNOLOGIA DO RIO GRANDE DO NORTE' WHERE ies_id = 1082;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSITARIO CNEC DE BENTO GONCALVES' WHERE ies_id = 1084;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE METODISTA CENTENARIO' WHERE ies_id = 1085;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSITARIO APARICIO CARVALHO' WHERE ies_id = 1087;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSITARIO CARLOS DRUMMOND DE ANDRADE' WHERE ies_id = 1100;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSITARIO EUROAMERICANO' WHERE ies_id = 1113;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE DE MIRASSOL' WHERE ies_id = 1118;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE PLANALTO DE FILOSOFIA CIENCIAS E LETRAS' WHERE ies_id = 1119;
            UPDATE modules.educacenso_ies SET nome = 'INSTITUTO FEDERAL DE EDUCACAO CIENCIA E TECNOLOGIA FLUMINENSE' WHERE ies_id = 1120;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE DOM PEDRO II DE BARREIRAS' WHERE ies_id = 1124;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSITARIO SANTO AGOSTINHO' WHERE ies_id = 1131;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSITARIO GAMA E SOUZA' WHERE ies_id = 1141;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE DE DIREITO DE VITORIA' WHERE ies_id = 1142;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE DE TECNOLOGIA SENAI THEOBALDO DE NIGRIS' WHERE ies_id = 1150;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE CNEC ITABORAI' WHERE ies_id = 1156;
            UPDATE modules.educacenso_ies SET nome = 'INSTITUTO FEDERAL DE EDUCACAO CIENCIA E TECNOLOGIA DA PARAIBA' WHERE ies_id = 1166;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE ESTACIO DO RIO GRANDE DO SUL ESTACIO FARGS' WHERE ies_id = 1175;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSITARIO SAO FRANCISCO DE BARREIRAS' WHERE ies_id = 1227;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE CNEC SANTO ANGELO' WHERE ies_id = 1231;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSITARIO UNIC' WHERE ies_id = 1233;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE DOCTUM DE SERRA' WHERE ies_id = 1243;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE DE CASTELO MULTIVIX CASTELO' WHERE ies_id = 1245;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSITARIO FBV WYDEN' WHERE ies_id = 1255;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE DE ADMINISTRACAO CIENCIAS EDUCACAO E LETRAS' WHERE ies_id = 1257;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE DE CASCAVEL' WHERE ies_id = 1258;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSITARIO ESTACIO DE RIBEIRAO PRETO' WHERE ies_id = 1270;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE SANTANNA DE SALTO' WHERE ies_id = 1272;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSITARIO CAMPO LIMPO PAULISTA' WHERE ies_id = 1273;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE DE TECNOLOGIA SENAI MARIO AMATO' WHERE ies_id = 1286;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE DE SANTO ANTONIO DA PLATINA' WHERE ies_id = 1291;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSITARIO DE ADAMANTINA' WHERE ies_id = 1292;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSITARIO DAS AMERICAS' WHERE ies_id = 1294;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE DE EDUCACAO E TECNOLOGIA IRACEMA' WHERE ies_id = 1295;
            UPDATE modules.educacenso_ies SET nome = 'INSTITUTO TAQUARITINGUENSE DE ENSINO SUPERIOR DR ARISTIDES DE CARVALHO SCHLOBACH' WHERE ies_id = 1300;
            UPDATE modules.educacenso_ies SET nome = 'INSTITUTO FEDERAL DE EDUCACAO CIENCIA E TECNOLOGIA GOIANO' WHERE ies_id = 1303;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE DE RIBEIRAO PIRES' WHERE ies_id = 1304;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE DE CIENCIAS JURIDICAS GERENCIAIS E EDUCACAO DE SINOP' WHERE ies_id = 1305;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE DE ENSINO SUPERIOR E FORMACAO INTEGRAL' WHERE ies_id = 1307;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE PROJECAO DE TAGUATINGA NORTE' WHERE ies_id = 1309;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE DE SUZANO' WHERE ies_id = 1313;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE DE CIENCIAS SOCIAIS APLICADAS DE MINAS GERAIS' WHERE ies_id = 1314;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSITARIO SUDOESTE PAULISTA' WHERE ies_id = 1317;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE UNINASSAU VITORIA DA CONQUISTA' WHERE ies_id = 1318;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE DE CIENCIAS ADMINISTR1S E CONTABEIS DA ZONA NORTE' WHERE ies_id = 1321;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSITARIO FACISA' WHERE ies_id = 1334;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSITARIO ASSIS GURGACZ' WHERE ies_id = 1336;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE DE CIENCIAS ADMINISTR1S DE PARANAIBA' WHERE ies_id = 1339;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSITARIO SOCIESC' WHERE ies_id = 1351;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSITARIO DE SANTA FE DO SUL' WHERE ies_id = 1356;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSITARIO UBAENSE OZANAM COELHO' WHERE ies_id = 1362;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSIARIO UNIFTC' WHERE ies_id = 1364;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE DE GUARANTA DO NORTE' WHERE ies_id = 1374;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE MARTHA FALCAO WYDEN' WHERE ies_id = 1381;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE PENTAGONO FAPEN' WHERE ies_id = 1387;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSITARIO SUMARE' WHERE ies_id = 1388;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE ANDREOTTI' WHERE ies_id = 1399;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE DA INDUSTRIA SAO JOSE DOS PINHAIS' WHERE ies_id = 1400;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE AREA1 WYDEN' WHERE ies_id = 1410;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE ANHANGUERA DE JUNDIAI' WHERE ies_id = 1412;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSITARIO SAO LUCAS' WHERE ies_id = 1414;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE CNEC CAMPO LARGO' WHERE ies_id = 1417;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE IDEAL WYDEN' WHERE ies_id = 1423;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSITARIO DA SERRA GAUCHA' WHERE ies_id = 1427;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSITARIO INGA' WHERE ies_id = 1430;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSITARIO DE ITAPIRA UNIESI' WHERE ies_id = 1434;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE NOSSA SENHORA DE FATIMA' WHERE ies_id = 1443;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE DE IBAITI' WHERE ies_id = 1449;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSITARIO DO CERRADOPATROCINIO' WHERE ies_id = 1450;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE PITAGORAS DO MARANHAO' WHERE ies_id = 1452;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE LOGOS INTERNACIONAL' WHERE ies_id = 1453;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSITARIO MARIO PALMERIO' WHERE ies_id = 1459;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSIARIO UNIFTC SALVADOR' WHERE ies_id = 1461;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE DE BARUERI' WHERE ies_id = 1463;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE CESUSC' WHERE ies_id = 1469;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE DE COMUNICACAO E DESIGN OSWALDO CRUZ' WHERE ies_id = 1476;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE JK MICHELANGELO' WHERE ies_id = 1477;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSITARIO UNIDOM BOSCO' WHERE ies_id = 1487;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE LUSOFONA DO RIO DE JANEIRO' WHERE ies_id = 1488;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSITARIO DE JAGUARIUNA' WHERE ies_id = 1490;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSITARIO ALVES FARIA' WHERE ies_id = 1493;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSITARIO CATOLICO DE VITORIA' WHERE ies_id = 1494;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE ANHANGUERA PITAGORAS DE JUNDIAI' WHERE ies_id = 1502;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSITARIO MAURICIO DE NASSAU DE MACEIO' WHERE ies_id = 1504;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE CNEC ITAJAI' WHERE ies_id = 1506;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSITARIO METROPOLITANO DE MARINGA' WHERE ies_id = 1508;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSITARIO ESTACIO DE BELO HORIZONTE ESTACIO BH' WHERE ies_id = 1509;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSITARIO ESTACIO DE SANTA CATARINA ESTACIO SANTA CATARINA' WHERE ies_id = 1510;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE PITAGORAS INSTITUTO CAMILLO FILHO' WHERE ies_id = 1513;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE ANHANGUERA DE TAGUATINGA' WHERE ies_id = 1518;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSITARIO DE PATO BRANCO' WHERE ies_id = 1519;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE ESTACIO DE BELEM ESTACIO BELEM' WHERE ies_id = 1521;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE OLGA METTIG' WHERE ies_id = 1524;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE CNEC JOINVILLE' WHERE ies_id = 1530;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE DE SERTAOZINHO' WHERE ies_id = 1532;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE DE CIENCIAS LETRAS E EDUCACAO DO NOROESTE DO PARANA' WHERE ies_id = 1534;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE DE PINHAIS' WHERE ies_id = 1535;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSITARIO PROJECAO' WHERE ies_id = 1538;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE DE BOITUVA' WHERE ies_id = 1545;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE UNINASSAU PARNAIBA' WHERE ies_id = 1552;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSITARIO DO VALE DO RIBEIRA' WHERE ies_id = 1554;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSITARIO SETE DE SETEMBRO' WHERE ies_id = 1556;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE DOCTUM DE JOAO MONLEVADE' WHERE ies_id = 1558;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSITARIO UNINOVAFAPI' WHERE ies_id = 1563;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADES DOCTUM DE CARATINGA' WHERE ies_id = 1568;
            UPDATE modules.educacenso_ies SET nome = 'INSTITUTO FEDERAL DE EDUCACAO CIENCIA E TECNOLOGIA SULRIOGRANDENSE' WHERE ies_id = 1578;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE DE SANTA LUZIA' WHERE ies_id = 1581;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE ENERGIA' WHERE ies_id = 1585;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSITARIO ESTACIO DE SAO LUIS' WHERE ies_id = 1590;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE ESTACIO MACAPA ESTACIO MACAPA' WHERE ies_id = 1591;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSITARIO UNA DE UBERLANDIA' WHERE ies_id = 1598;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSITARIO PRESIDENTE TANCREDO DE ALMEIDA NEVES' WHERE ies_id = 1599;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE ASSIS GURGACZ' WHERE ies_id = 1612;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSITARIO SOCIESC DE BLUMENAU' WHERE ies_id = 1618;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE DE OLIMPIA' WHERE ies_id = 1619;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE DOCTUM DA SERRA' WHERE ies_id = 1634;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSITARIO AGES' WHERE ies_id = 1640;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSITARIO SOCIAL DA BAHIA' WHERE ies_id = 1641;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE J SIMOES ENSINO SUPERIOR' WHERE ies_id = 1650;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSITARIO UNISEP' WHERE ies_id = 1657;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSITARIO DA GRANDE FORTALEZA' WHERE ies_id = 1658;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSITARIO ESTACIO DE BRASILIA ESTACIO BRASILIA' WHERE ies_id = 1660;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSITARIO UNIHORIZONTES' WHERE ies_id = 1666;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE PITAGORAS DE MINAS GERAIS' WHERE ies_id = 1668;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSITARIO SAO MIGUEL' WHERE ies_id = 1676;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE UNIRB MOSSORO' WHERE ies_id = 1680;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSITARIO MAURICIO DE NASSAU DE TERESINA' WHERE ies_id = 1683;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSITARIO FACOL' WHERE ies_id = 1697;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSITARIO ESTACIO DA AMAZONIA' WHERE ies_id = 1702;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSITARIO TIRADENTES DE PERNAMBUCO' WHERE ies_id = 1709;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE ANHANGUERA DE NEGOCIOS E TECNOLOGIAS DA INFORMACAO' WHERE ies_id = 1710;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSITARIO UNIAO DAS AMERICAS' WHERE ies_id = 1716;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE DE IMPERATRIZ WYDEN' WHERE ies_id = 1717;
            UPDATE modules.educacenso_ies SET nome = 'ESCOLA SUPERIOR DE ADMINISTRACAO E GESTAO STRONG' WHERE ies_id = 1723;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSITARIO SANTA AMELIA' WHERE ies_id = 1726;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE INTEGRAL DIFERENCIAL WYDEN' WHERE ies_id = 1734;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSITARIO DOUTOR LEAO SAMPAIO' WHERE ies_id = 1735;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE SAO LUCAS PORTO VELHO' WHERE ies_id = 1738;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE FORTIUM SAO SEBASTIAO' WHERE ies_id = 1739;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE INTERATIVA DE SAO PAULO' WHERE ies_id = 1745;
            UPDATE modules.educacenso_ies SET nome = 'ESCOLA SUPERIOR DE ADMINISTRACAO MARKETING E COMUNICACAO DE GOIANIA' WHERE ies_id = 1757;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE DE TECNOLOGIA E CIENCIAS' WHERE ies_id = 1771;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSITARIO FANOR WYDEN' WHERE ies_id = 1772;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSITARIO FAI' WHERE ies_id = 1773;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSITARIO FAVIP WYDEN' WHERE ies_id = 1775;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE ANHANGUERA DE TECNOLOGIA DE JUNDIAI' WHERE ies_id = 1776;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSITARIO LEONARDO DA VINCI' WHERE ies_id = 1777;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE DE EDUCACAO CIENCIAS E LETRAS SAO JUDAS TADEU' WHERE ies_id = 1778;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE DE ARTES CIENCIAS E TECNOLOGIAS' WHERE ies_id = 1782;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE DO SUL DA BAHIA' WHERE ies_id = 1790;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADES LONDRINA' WHERE ies_id = 1797;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE BRASILIA DE TECNOLOGIA CIENCIAS E EDUCACAO' WHERE ies_id = 1799;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE REGES DE REALEZA' WHERE ies_id = 1800;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSITARIO DOS GUARARAPES' WHERE ies_id = 1805;
            UPDATE modules.educacenso_ies SET nome = 'INSTITUTO FEDERAL DE EDUCACAO CIENCIA E TECNOLOGIA DO CEARA' WHERE ies_id = 1807;
            UPDATE modules.educacenso_ies SET nome = 'INSTITUTO FEDERAL DE EDUCACAO CIENCIA E TECNOLOGIA DO ESPIRITO SANTO' WHERE ies_id = 1808;
            UPDATE modules.educacenso_ies SET nome = 'INSTITUTO FEDERAL DE EDUCACAO CIENCIA E TECNOLOGIA DE PERNAMBUCO' WHERE ies_id = 1809;
            UPDATE modules.educacenso_ies SET nome = 'INSTITUTO FEDERAL DE EDUCACAO CIENCIA E TECNOLOGIA DE SAO PAULO' WHERE ies_id = 1810;
            UPDATE modules.educacenso_ies SET nome = 'INSTITUTO FEDERAL DE EDUCACAO CIENCIA E TECNOLOGIA DE GOIAS' WHERE ies_id = 1811;
            UPDATE modules.educacenso_ies SET nome = 'INSTITUTO FEDERAL DE EDUCACAO CIENCIA E TECNOLOGIA DO AMAZONAS' WHERE ies_id = 1812;
            UPDATE modules.educacenso_ies SET nome = 'INSTITUTO FEDERAL DE EDUCACAO CIENCIA E TECNOLOGIA DO PARA' WHERE ies_id = 1813;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSITARIO FARIAS BRITO' WHERE ies_id = 1819;
            UPDATE modules.educacenso_ies SET nome = 'INSTITUTO FEDERAL DE EDUCACAO CIENCIA E TECNOLOGIA DO PIAUI' WHERE ies_id = 1820;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE DE IBITINGA' WHERE ies_id = 1831;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE DE COLINAS DO TOCANTINS' WHERE ies_id = 1835;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSITARIO FUNDACAO DE ENSINO OCTAVIO BASTOS FEOB' WHERE ies_id = 1836;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSITARIO ANTONIO EUFRASIO DE TOLEDO DE PRESIDENTE PRUDENTE TOLEDO PRUDENTE' WHERE ies_id = 1841;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE PITAGORAS DE IMPERATRIZ' WHERE ies_id = 1847;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE SANTA MARIA DA GLORIA' WHERE ies_id = 1850;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSITARIO UNIBTA' WHERE ies_id = 1853;
            UPDATE modules.educacenso_ies SET nome = 'CLARETIANO CENTRO UNIVERSITARIO' WHERE ies_id = 1854;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE DOM PEDRO II DE JEQUIE' WHERE ies_id = 1858;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE MANTENENSE DOS VALES GERAIS (INTERVALE)' WHERE ies_id = 1863;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE ALVORADA PAULISTA' WHERE ies_id = 1865;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE DE CIENCIAS EDUCACIONAIS E EMPRESARIAIS DE NATAL' WHERE ies_id = 1866;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE SANTOS DUMONT' WHERE ies_id = 1867;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE DE FILOSOFIA CIENCIAS E LETRAS DE IBITINGA' WHERE ies_id = 1875;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSITARIO UNIFACEAR' WHERE ies_id = 1879;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSITARIO UNIFAS' WHERE ies_id = 1883;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE DE RANCHARIA' WHERE ies_id = 1884;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSITARIO UNIDADE DE ENSINO SUPERIOR DOM BOSCO' WHERE ies_id = 1885;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE INTEGRADA DE GOIAS' WHERE ies_id = 1890;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSITARIO DE EXCELENCIA ENIAC' WHERE ies_id = 1892;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE UNIRB FEIRA DE SANTANA' WHERE ies_id = 1893;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE DE NOVA ESPERANCA' WHERE ies_id = 1899;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSITARIO DO PARANA' WHERE ies_id = 1900;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADES DOCTUM DE IPATINGA' WHERE ies_id = 1909;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE UNINASSAU LAURO DE FREITAS' WHERE ies_id = 1910;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSITARIO FAMINAS' WHERE ies_id = 1913;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSITARIO DO VALE DO IGUACU' WHERE ies_id = 1927;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE CNEC ILHA DO GOVERNADOR' WHERE ies_id = 1928;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE DE UMUARAMA' WHERE ies_id = 1938;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE JK SOBRADINHO' WHERE ies_id = 1943;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSITARIO DE PAULINIA' WHERE ies_id = 1949;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSITARIO CATHEDRAL' WHERE ies_id = 1952;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE REGIONAL BRASILEIRA MACEIO' WHERE ies_id = 1956;
            UPDATE modules.educacenso_ies SET nome = 'INSTITUTO TECNOLOGICO E DAS CIENCIAS SOCIAIS APLICADAS E DA SAUDE DO CENTRO EDUC N SRª AUXILIADORA' WHERE ies_id = 1961;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE DE TECNOLOGIA EM HOTELARIA GASTRONOMIA E TURISMO DE SAO PAULO' WHERE ies_id = 1964;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE BRASILEIRA DE TECNOLOGIA' WHERE ies_id = 1968;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE DE SAO CAETANO DO SUL' WHERE ies_id = 1972;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSITARIO FAMETRO' WHERE ies_id = 1978;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSITARIO UNIFACIG' WHERE ies_id = 1984;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSITARIO ESTACIO JUIZ DE FORA ESTACIO JUIZ DE FORA' WHERE ies_id = 1986;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSITARIO AVANTIS' WHERE ies_id = 1988;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE IDEAL DE PATOS' WHERE ies_id = 1993;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE JK UNIDADE II GAMA' WHERE ies_id = 2021;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSITARIO FG' WHERE ies_id = 2023;
            UPDATE modules.educacenso_ies SET nome = 'FALCUDADE DE CIENCIAS ECONOMICAS CONTABEIS E ADMINISTR1S DE BELO HORIZONTE' WHERE ies_id = 2028;
            UPDATE modules.educacenso_ies SET nome = 'UNIAO LATINOAMERICANA DE TECNOLOGIA' WHERE ies_id = 2035;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSITARIO VALE DO SALGADO' WHERE ies_id = 2043;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE DE CIENCIAS E EMPREENDEDORISMO' WHERE ies_id = 2067;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSITARIO UNIRB' WHERE ies_id = 2076;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE CNEC NOVA PETROPOLIS' WHERE ies_id = 2084;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSITARIO DE SALVADOR' WHERE ies_id = 2085;
            UPDATE modules.educacenso_ies SET nome = 'INSTITUTO SUPERIOR DE EDUCACAO PROSABER' WHERE ies_id = 2091;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE DOCTUM DE MANHUACU DOCTUM' WHERE ies_id = 2096;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE EXCELENCIA' WHERE ies_id = 2098;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSITARIO INTA' WHERE ies_id = 2111;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSITARIO ESTACIO DE SERGIPE' WHERE ies_id = 2122;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSITARIO MAX PLANCK' WHERE ies_id = 2123;
            UPDATE modules.educacenso_ies SET nome = 'ESCOLA DE DIREITO DE SAO PAULO FGV DIREITO SP' WHERE ies_id = 2128;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE DE SAO BERNARDO DO CAMPO' WHERE ies_id = 2131;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSITARIO UNINORTE' WHERE ies_id = 2132;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE DE CIENCIAS EDUCACAO E TEOLOGIA DO NORTE DO BRASIL' WHERE ies_id = 2133;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE ASSEMBLEIANA DO BRASIL' WHERE ies_id = 2134;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSITARIO CATOLICA DE QUIXADA' WHERE ies_id = 2135;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE NOSSA SENHORA DE LOURDES' WHERE ies_id = 2140;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADES BATISTA DO PARANA' WHERE ies_id = 2141;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE MULTIEDUC1' WHERE ies_id = 2142;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE PROMOVE DE TECNOLOGIA' WHERE ies_id = 2145;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSITARIO CEUNI FAMETRO' WHERE ies_id = 2147;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSITARIO DO PIAUI' WHERE ies_id = 2150;
            UPDATE modules.educacenso_ies SET nome = 'INSTITUTO SUPERIOR DE EDUCACAO SANTANA' WHERE ies_id = 2157;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE SANT ANA' WHERE ies_id = 2160;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE EUGENIO GOMES' WHERE ies_id = 2163;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSITARIO DANTE' WHERE ies_id = 2175;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE INSTITUTO PAULISTA DE ENSINO' WHERE ies_id = 2177;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE CNEC GRAVATAI' WHERE ies_id = 2184;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE REGES DE TUPI PAULISTA' WHERE ies_id = 2205;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE DOCTUM DE JUIZ DE FORA' WHERE ies_id = 2220;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSITARIO DO RIO SAO FRANCISCO UNIRIOS' WHERE ies_id = 2222;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSITARIO DO SUDESTE MINEIRO' WHERE ies_id = 2241;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE PAULISTA SAO JOSE' WHERE ies_id = 2247;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE STELLA MARIS FSM' WHERE ies_id = 2256;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE SANTO AGOSTINHO' WHERE ies_id = 2275;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSITARIO METROCAMP WYDEN' WHERE ies_id = 2279;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE DE CIENCIAS HUMANAS BIOLOGICAS E DA SAUDE' WHERE ies_id = 2293;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE KENNEDY DE MINAS GERAIS FKMG' WHERE ies_id = 2311;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE ANHANGUERA DE SAO JOSESC' WHERE ies_id = 2324;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE CANDIDO RONDON' WHERE ies_id = 2330;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE CNEC RIO DAS OSTRAS' WHERE ies_id = 2334;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSITARIO MONTES BELOS' WHERE ies_id = 2336;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSITARIO U:VERSE' WHERE ies_id = 2343;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSITARIO CATOLICA DO TOCANTINS' WHERE ies_id = 2365;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE SAO LEOPOLDO MANDIC' WHERE ies_id = 2368;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE ESTACIO DO AMAPA ESTACIO AMAPA' WHERE ies_id = 2380;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE DE TECNOLOGIA E CIENCIAS' WHERE ies_id = 2402;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSITARIO TABOSA DE ALMEIDA' WHERE ies_id = 2409;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE LUSOFONA DA BAHIA' WHERE ies_id = 2427;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE ESTACIO DE IBIUNA' WHERE ies_id = 2431;
            UPDATE modules.educacenso_ies SET nome = 'INSTITUTO DE ENSINO SUPERIOR BRASILEIRO' WHERE ies_id = 2436;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE FUNORTE DE JANAUBA' WHERE ies_id = 2443;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE UNIRB BARREIRAS' WHERE ies_id = 2444;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE IBMEC SAO PAULO' WHERE ies_id = 2465;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE DOM LUCIANO MENDES' WHERE ies_id = 2475;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSITARIO FUNVIC' WHERE ies_id = 2494;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSITARIO ATENEU' WHERE ies_id = 2497;
            UPDATE modules.educacenso_ies SET nome = 'FASS FACULDADE SOCIAL SUL AMERICANA' WHERE ies_id = 2499;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE POSITIVO LONDRINA' WHERE ies_id = 2513;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE DE CIENCIAS EDUCACIONAIS DO RIO GRANDE DO NORTE' WHERE ies_id = 2514;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE DE GUARULHOS' WHERE ies_id = 2530;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE DE TEOLOGIA FILOSOFIA E CIENCIAS HUMANAS GAMALIEL' WHERE ies_id = 2548;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE DE IBIUNA' WHERE ies_id = 2549;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE DOM PEDRO II LUIS EDUARDO MAGALHAES' WHERE ies_id = 2553;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE DE CIENCIAS ADMINISTR1S' WHERE ies_id = 2561;
            UPDATE modules.educacenso_ies SET nome = 'ABEU CENTRO UNIVERSITARIO' WHERE ies_id = 2565;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSITARIO REDENTOR' WHERE ies_id = 2571;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE REGIONAL DE FILOSOFIA CIENCIAS E LETRAS DE CANDEIAS' WHERE ies_id = 2572;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSITARIO ATENAS' WHERE ies_id = 2579;
            UPDATE modules.educacenso_ies SET nome = 'EPGE ESCOLA BRASILEIRA DE ECONOMIA E FINANCAS' WHERE ies_id = 2591;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSITARIO META' WHERE ies_id = 2613;
            UPDATE modules.educacenso_ies SET nome = 'AJES FACULDADE DO VALE DO JURUENA' WHERE ies_id = 2629;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE DE CIENCIAS ADMINISTR1S SOCIAIS E DA SAUDE DE BELO HORIZONTE' WHERE ies_id = 2655;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE DE RECIFE' WHERE ies_id = 2656;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE CATOLICA IMACULADA CONCEICAO DO RECIFE' WHERE ies_id = 2723;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE UBS' WHERE ies_id = 2793;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE MERIDIONAL RS' WHERE ies_id = 2821;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE SUCESSO' WHERE ies_id = 2832;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE DE CAIEIRAS' WHERE ies_id = 2879;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE UNIVERITAS UNIVERSUS VERITAS DE BELO HORIZONTE VERITAS BH' WHERE ies_id = 2885;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE LIBERDADE EDUCACAO E TECNOLOGIA' WHERE ies_id = 2895;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSITARIO NATALENSE' WHERE ies_id = 2908;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE PAN AMAZONICA' WHERE ies_id = 2911;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE DE BELO HORIZONTE' WHERE ies_id = 2927;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSITARIO FADERGS' WHERE ies_id = 2950;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE DE IBIPORA' WHERE ies_id = 3027;
            UPDATE modules.educacenso_ies SET nome = 'INSTITUTO FEDERAL DE EDUCACAO CIENCIA E TECNOLOGIA DE ALAGOAS' WHERE ies_id = 3160;
            UPDATE modules.educacenso_ies SET nome = 'INSTITUTO FEDERAL DE EDUCACAO CIENCIA E TECNOLOGIA DO SERTAO PERNAMBUCANO' WHERE ies_id = 3161;
            UPDATE modules.educacenso_ies SET nome = 'INSTITUTO FEDERAL DE EDUCACAO CIENCIA E TECNOLOGIA DE SANTA CATARINA' WHERE ies_id = 3162;
            UPDATE modules.educacenso_ies SET nome = 'INSTITUTO FEDERAL DE EDUCACAO CIENCIA E TECNOLOGIA DO RIO DE JANEIRO' WHERE ies_id = 3163;
            UPDATE modules.educacenso_ies SET nome = 'INSTITUTO FEDERAL DE EDUCACAO CIENCIA E TECNOLOGIA DE MATO GROSSO' WHERE ies_id = 3164;
            UPDATE modules.educacenso_ies SET nome = 'INSTITUTO FEDERAL DE EDUCACAO CIENCIA E TECNOLOGIA DO TRIANGULO MINEIRO' WHERE ies_id = 3165;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE ESTACIO DE FLORIANOPOLIS ESTACIO FLORIANOPOLIS' WHERE ies_id = 3170;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE ATTICUS' WHERE ies_id = 3180;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE UNIRB ARAPIRACA' WHERE ies_id = 3182;
            UPDATE modules.educacenso_ies SET nome = 'INSTITUTO FEDERAL DE EDUCACAO CIENCIA E TECNOLOGIA DE SERGIPE' WHERE ies_id = 3183;
            UPDATE modules.educacenso_ies SET nome = 'INSTITUTO FEDERAL DE EDUCACAO CIENCIA E TECNOLOGIA DE RORAIMA' WHERE ies_id = 3184;
            UPDATE modules.educacenso_ies SET nome = 'INSTITUTO FEDERAL DE EDUCACAO CIENCIA E TECNOLOGIA DO NORTE DE MINAS GERAIS' WHERE ies_id = 3188;
            UPDATE modules.educacenso_ies SET nome = 'INSTITUTO FEDERAL DE EDUCACAO CIENCIA E TECNOLOGIA DE MINAS GERAIS' WHERE ies_id = 3189;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE DE CIENCIAS E TECNOLOGIA DE VICOSA' WHERE ies_id = 3205;
            UPDATE modules.educacenso_ies SET nome = 'FI FACULDADE IGUACU' WHERE ies_id = 3232;
            UPDATE modules.educacenso_ies SET nome = 'INSTITUTO FEDERAL DE EDUCACAO CIENCIA E TECNOLOGIA DO SUDESTE DE MINAS GERAIS' WHERE ies_id = 3279;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSITARIO FAVENI' WHERE ies_id = 3294;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE SENAC FLORIANOPOLIS' WHERE ies_id = 3295;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE REGES DE JUNQUEIROPOLIS' WHERE ies_id = 3302;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE INVEST DE CIENCIAS E TECNOLOGIA' WHERE ies_id = 3303;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSITARIO DE PATOS' WHERE ies_id = 3304;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE DE RIO CLARO' WHERE ies_id = 3307;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE DE EDUCACAO AVANCADA DO NOROESTE CAPIXABA' WHERE ies_id = 3311;
            UPDATE modules.educacenso_ies SET nome = 'INSTITUTO UNIVERSITARIO UNA DE CATALAO' WHERE ies_id = 3319;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSITARIO UNIFTEC' WHERE ies_id = 3333;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE IDEAU DE GETULIO VARGAS' WHERE ies_id = 3339;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE EVANGELICA RAIZES' WHERE ies_id = 3389;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE DE FILOSOFIA CIENCIAS E LETRAS DE CARANGOLA' WHERE ies_id = 3473;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE BOAS NOVAS DE CIENCIAS TEOLOGICAS SOCIAIS E BIOTECNOLOGICAS' WHERE ies_id = 3397;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE DE PENAPOLIS' WHERE ies_id = 3400;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE DE JANDIRA' WHERE ies_id = 3411;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE DOM PEDRO II DE SERGIPE' WHERE ies_id = 3427;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE ALFA AMERICA' WHERE ies_id = 3428;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE UBERLANDENSE DE NUCLEOS INTEGRADOS DE ENSINO SERVICO SOCIAL E APRENDIZAGEM' WHERE ies_id = 3430;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADES INTEGRADAS DE CIENCIAS HUMANAS SAUDE E EDUCACAO DE GUARULHOS' WHERE ies_id = 3432;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE DE SAUDE E HUMANIDADES IBITURUNA' WHERE ies_id = 3434;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE SOCIESC DE BALNEARIO CAMBORIU' WHERE ies_id = 3437;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSITARIO DA VITORIA DE SANTO ANTAO' WHERE ies_id = 3515;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE SOCIESC DE JARAGUA DO SUL' WHERE ies_id = 3518;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE EVANGELICA DE TECNOLOGIA CIENCIAS E BIOTECNOLOGIA DA CGADB' WHERE ies_id = 3525;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE FAE SEVIGNE PORTO ALEGRE' WHERE ies_id = 3538;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE DE TAPEJARA' WHERE ies_id = 3541;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE 1' WHERE ies_id = 3575;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSITARIO DOM PEDRO II' WHERE ies_id = 3588;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE DE CIENCIA TECNOLOGIA E EDUCACAO' WHERE ies_id = 3594;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSITARIO AUTONOMO DO BRASIL' WHERE ies_id = 3602;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSITARIO ICESP' WHERE ies_id = 3610;
            UPDATE modules.educacenso_ies SET nome = 'ESCOLA DE CIENCIAS SOCIAIS' WHERE ies_id = 3614;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE LUSOFONA DE SAO PAULO' WHERE ies_id = 3618;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE DO COMPLEXO EDUCACIONAL SANTO ANDRE' WHERE ies_id = 3625;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADES INTEGRADAS DO RIO GRANDE DO NORTE FANORTES' WHERE ies_id = 3643;
            UPDATE modules.educacenso_ies SET nome = 'INSTITUTO DE ENSINO SUPERIOR DE CUIABA' WHERE ies_id = 3648;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSITARIO CIDADE VERDE' WHERE ies_id = 3649;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE FORTIUM DE BRASILIA' WHERE ies_id = 3663;
            UPDATE modules.educacenso_ies SET nome = 'SINAL FACULDADE DE CIENCIAS HUMANAS E SOCIAIS' WHERE ies_id = 3675;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE PADRE DOURADO FORTALEZA' WHERE ies_id = 3680;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE FAMERCOSUL' WHERE ies_id = 3697;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE PITAGORAS BACABAL MEARIM' WHERE ies_id = 3741;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE DE JACAREI' WHERE ies_id = 3743;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE BRASILIA DE SAO PAULO' WHERE ies_id = 3749;
            UPDATE modules.educacenso_ies SET nome = 'ALFA FACULDADE DE ALMENARA' WHERE ies_id = 3756;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE IBGEN' WHERE ies_id = 3768;
            UPDATE modules.educacenso_ies SET nome = 'INSTITUTO UVB BR' WHERE ies_id = 3775;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE DE FRUTAL' WHERE ies_id = 3793;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSITARIO ZEN' WHERE ies_id = 3801;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE DE JAU' WHERE ies_id = 3803;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE UNINASSAU JOAO PESSOA' WHERE ies_id = 3817;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE DE SALVADOR' WHERE ies_id = 3826;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE MARINHO PAULISTA' WHERE ies_id = 3837;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE ESTACIO DE JOAO PESSOA ESTACIO DE JOAO PESSOA' WHERE ies_id = 3838;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE IPEMED DE CIENCIAS MEDICAS' WHERE ies_id = 3839;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE JK PLANO PILOTO' WHERE ies_id = 3992;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE UNINASSAU NATAL' WHERE ies_id = 3853;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE IDEAL DE BRASILIA' WHERE ies_id = 3854;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE COOPER1 DE GOIANIA' WHERE ies_id = 3863;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSITARIO UNIRB ALAGOINHAS' WHERE ies_id = 3864;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE UNYLEYA' WHERE ies_id = 3876;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE LINEAR' WHERE ies_id = 3877;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSITARIO MAURICIO DE NASSAU DE CAMPINA GRANDE' WHERE ies_id = 3879;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE PAULISTA DE COMUNICACAO' WHERE ies_id = 3896;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSITARIO ARNALDO HORACIO FERREIRA' WHERE ies_id = 3921;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE ALIANCA DE ITABERAI' WHERE ies_id = 3939;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE SENAC TUBARAO' WHERE ies_id = 3946;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE SENAC CHAPECO' WHERE ies_id = 3947;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE SENAC BLUMENAU' WHERE ies_id = 3948;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE EDUCACIONAL JURIDICA E GERENCIAL DE OLIVEIRA' WHERE ies_id = 3954;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSITARIO SENAI CIMATEC' WHERE ies_id = 3962;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE DE TECNOLOGIA ENG MARCELO SILVA GUIMARAES' WHERE ies_id = 3965;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE JK BRASILIA SAMAMBAIA' WHERE ies_id = 3980;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE DE CURITIBA' WHERE ies_id = 3981;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE INSTITUTO SUPERIOR DE EDUCACAO DO PARANA FAINSEP' WHERE ies_id = 3986;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE SAO BERNARDO DE TECNOLOGIA' WHERE ies_id = 3990;
            UPDATE modules.educacenso_ies SET nome = 'FATECE FACULDADE DE TECNOLOGIA CIENCIAS E EDUCACAO' WHERE ies_id = 4007;
            UPDATE modules.educacenso_ies SET nome = 'UNI METROPOLITANA FACULDADES DE CIENCIAS HUMANAS E DE BIOTECNOLOGIA DA SAUDE' WHERE ies_id = 4012;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE DE SANTA BARBARA D OESTE' WHERE ies_id = 4029;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSITARIO PITAGORAS DE FORTALEZA' WHERE ies_id = 4037;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE JK BRASILIA RECANTO DAS EMAS' WHERE ies_id = 4042;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSITARIO SOCIESC DE CURITIBA' WHERE ies_id = 4045;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE SKEMA BUSINESS SCHOOL' WHERE ies_id = 4053;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE QI BRASIL' WHERE ies_id = 4077;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE DE TECNOLOGIA FTEC' WHERE ies_id = 4096;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE DE TECNOLOGIA FTEC' WHERE ies_id = 4097;
            UPDATE modules.educacenso_ies SET nome = 'INSTITUTO FEDERAL DE EDUCACAO CIENCIA E TECNOLOGIA FARROUPILHA' WHERE ies_id = 4098;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE EVANGELICA DE CERES' WHERE ies_id = 4113;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSITARIO JOAQUIM NABUCO DE PAULISTA' WHERE ies_id = 4118;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSITARIO MAURICIO DE NASSAU DE ARACAJU' WHERE ies_id = 4121;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE DE GESTAO E INOVACAO' WHERE ies_id = 4123;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE UNINASSAU MANAUS' WHERE ies_id = 4135;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSITARIO JOAQUIM NABUCO DE RECIFE' WHERE ies_id = 4153;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE SENAC GOIAS' WHERE ies_id = 4162;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE ESTACIO DE CARAPICUIBA' WHERE ies_id = 4169;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE UNINASSAU ALIANCA REDENCAO' WHERE ies_id = 4197;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE MORGANA POTRICH' WHERE ies_id = 4198;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE JK BRASILIA RECANTO DAS EMAS II' WHERE ies_id = 4199;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADES INTEGRADAS DO BRASIL UNIFUTURO' WHERE ies_id = 4201;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE DE TECNOLOGIA E CIENCIAS DE MINAS GERAIS' WHERE ies_id = 4204;
            UPDATE modules.educacenso_ies SET nome = 'ESCOLA SUPERIOR DE ADMINISTRACAO MARKETING E COMUNICACAO DO MORUMBI' WHERE ies_id = 4210;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE ESAMC SAO PAULO ESAMC' WHERE ies_id = 4211;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE NACIONAL DE RIO DO SUL' WHERE ies_id = 4239;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE DE CIENCIAS GERENCIAIS ALVES FORTES JUIZ DE FORA' WHERE ies_id = 4250;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSITARIO FIPMOC' WHERE ies_id = 4256;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE ESTACIO DO AMAZONAS ESTACIO AMAZONAS' WHERE ies_id = 4277;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE DE TIETE' WHERE ies_id = 4293;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE SENAC JARAGUA DO SUL' WHERE ies_id = 4294;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE EFICAZ' WHERE ies_id = 4330;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE QUALITTAS' WHERE ies_id = 4357;
            UPDATE modules.educacenso_ies SET nome = 'INSTITUTO FEDERAL DE EDUCACAO CIENCIA E TECNOLOGIA DO SUL DE MINAS GERAIS' WHERE ies_id = 4358;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSITARIO DE MINEIROS' WHERE ies_id = 4396;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE JK UNIDADE I GAMA' WHERE ies_id = 4416;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSITARIO UNIGRAN CAPITAL' WHERE ies_id = 4429;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE DE ENFERMAGEM NOVA ESPERANCA DE MOSSORO FACENE/RN' WHERE ies_id = 4431;
            UPDATE modules.educacenso_ies SET nome = 'COOENSINO COOPER1 DE ENSINO UNIVERSAL DOIS MIL' WHERE ies_id = 4439;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE AMERICA LATINA DE IJUI' WHERE ies_id = 4443;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSITARIO METROPOLITANO DA AMAZONIA' WHERE ies_id = 4450;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSITARIO PITAGORAS DE MARABA' WHERE ies_id = 4452;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSITARIO TIRADENTES' WHERE ies_id = 4530;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE FACESE' WHERE ies_id = 4584;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE FUTURA' WHERE ies_id = 4597;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE DE JUNDIAI' WHERE ies_id = 4598;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE DE CORNELIO PROCOPIO' WHERE ies_id = 4605;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE INNOVARE' WHERE ies_id = 4629;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE IDEAU DE CAXIAS DO SUL' WHERE ies_id = 4632;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE IDEAU DE PASSO FUNDO' WHERE ies_id = 4633;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE UNIBF' WHERE ies_id = 4661;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSITARIO BRASILEIRO' WHERE ies_id = 4702;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE DE CIENCIAS HUMANAS DO ESTADO DE SAO PAULO' WHERE ies_id = 4724;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE DE TECNOLOGIA E CIENCIAS DO ALTO PARANAIBA' WHERE ies_id = 4740;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE UNINASSAU OLINDA NASSAU OLINDA' WHERE ies_id = 4742;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE DE BRUSQUE' WHERE ies_id = 4748;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE ALFA UMUARAMA' WHERE ies_id = 4765;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE DE CIENCIAS DA SAUDE DE UNAI' WHERE ies_id = 4780;
            UPDATE modules.educacenso_ies SET nome = 'INSTITUTO FEDERAL DE EDUCACAO CIENCIA E TECNOLOGIA DO TOCANTINS' WHERE ies_id = 4786;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE PROMINAS DE MONTES CLAROS' WHERE ies_id = 4821;
            UPDATE modules.educacenso_ies SET nome = 'INSTITUTO LABOR1' WHERE ies_id = 4824;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE CATOLICA DO RIO GRANDE DO NORTE' WHERE ies_id = 4847;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSITARIO TOCANTINENSE PRESIDENTE ANTONIO CARLOS' WHERE ies_id = 4849;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSITARIO FASIPE' WHERE ies_id = 4901;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE SENAI DE TECNOLOGIA EUVALDO LODI' WHERE ies_id = 4904;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE SENAI DE TECNOLOGIA JOSE FAGUNDES NETTO' WHERE ies_id = 4907;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE SENAI DE TECNOLOGIA FIDELIS REIS' WHERE ies_id = 4909;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE ESTACIO DE CASTANHAL' WHERE ies_id = 4915;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE ANGLO' WHERE ies_id = 4917;
            UPDATE modules.educacenso_ies SET nome = 'ESCOLA SUPERIOR DE ADMINISTRACAO E GESTAO STRONG DA BAIXADA SANTISTA' WHERE ies_id = 4943;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE CORPOR1 CESPI' WHERE ies_id = 4958;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSITARIO DE CIENCIAS E TECNOLOGIA DO MARANHAO' WHERE ies_id = 4964;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE EDUCAMAIS' WHERE ies_id = 4995;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE AGORA ADMINISTRACAO EDUCACAO E CULTURA' WHERE ies_id = 5000;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE SAO BRAZ' WHERE ies_id = 5025;
            UPDATE modules.educacenso_ies SET nome = 'INSTITUTO FEDERAL DE EDUCACAO CIENCIA E TECNOLOGIA CATARINENSE' WHERE ies_id = 5036;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE UNIAO ARARUAMA DE ENSINO SS LTDA' WHERE ies_id = 5112;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE SENAC CACADOR' WHERE ies_id = 5131;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE SENAC SAO MIGUEL DO OESTE' WHERE ies_id = 5133;
            UPDATE modules.educacenso_ies SET nome = 'INSTITUTO ASSIS GURGACZ' WHERE ies_id = 5186;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSITARIO PADRE ALBINO' WHERE ies_id = 5215;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE ANHANGUERA DE EDUCACAO CIENCIAS E TECNOLOGIA DE SOROCABA' WHERE ies_id = 5216;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE DOCTUM DE CARANGOLA' WHERE ies_id = 5276;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE ANHANGUERA DE CIENCIAS E TECNOLOGIA DE BRASILIA' WHERE ies_id = 5290;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSITARIO UNIFAAT' WHERE ies_id = 5312;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADES DOCTUM DE GUARAPARI' WHERE ies_id = 5314;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE UNIRB ARACAJU' WHERE ies_id = 5362;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSITARIO DOCTUM DE TEOFILO OTONI' WHERE ies_id = 5370;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE SANTISTA FASAN' WHERE ies_id = 5388;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSITARIO OPET' WHERE ies_id = 5403;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSITARIO DO PLANALTO CENTRAL APPARECIDO DOS SANTOS' WHERE ies_id = 5439;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE DE EDUCACAO TECNOLOGIA E ADMINISTRACAO DE CAARAPO' WHERE ies_id = 5444;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE DE CIENCIAS E TECNOLOGIA DA BAHIA' WHERE ies_id = 5473;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSITARIO CAMPO REAL' WHERE ies_id = 5511;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE INTER1 DE TECNOLOGIA E CIENCIAS' WHERE ies_id = 5531;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE DE CIENCIAS CONTABEIS E ADMINISTR1S DE CACHOEIRO DE ITAPEMIRIM' WHERE ies_id = 5533;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSITARIO ETEP' WHERE ies_id = 5669;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSITARIO DO VALE DO ARAGUAIA' WHERE ies_id = 5670;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE OBOE FACO' WHERE ies_id = 10016;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE DE TECNOLOGIA SENAI MATO GROSSO' WHERE ies_id = 10116;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE DE SANTA RITA DO PASSA QUATRO' WHERE ies_id = 10418;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE UNINABUCO SAO LOURENCO DA MATA' WHERE ies_id = 10588;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE UNIAO ARARUAMA DE ENSINO S/S LTDA' WHERE ies_id = 10836;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE DE INOVACAO DO PARANA' WHERE ies_id = 10846;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE CENTRO OESTE DO PARANA' WHERE ies_id = 11007;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADES NETWORK CAMPUS SUMARE' WHERE ies_id = 11586;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE APOENA' WHERE ies_id = 11593;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE SANTA RITA DE CHAPECO' WHERE ies_id = 11604;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE ANHANGUERA PITAGORAS VOTORANTIM' WHERE ies_id = 11750;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE SUDOESTE PAULISTA TATUI FSP' WHERE ies_id = 11752;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE INSPIRAR' WHERE ies_id = 11818;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE FORTIUM DE SANTA MARIA' WHERE ies_id = 11895;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE DE TECNOLOGIA INED UNIDADE VENDA NOVA' WHERE ies_id = 12005;
            UPDATE modules.educacenso_ies SET nome = 'ESCOLA DE DIREITO E DE ADMINISTRACAO PUBLICA DO IDP' WHERE ies_id = 12247;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE MAURICIO DE NASSAU DE MACEIO' WHERE ies_id = 12415;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE DA SERRA GAUCHA DE BENTO GONCALVES' WHERE ies_id = 12523;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE SETE LAGOAS' WHERE ies_id = 12620;
            UPDATE modules.educacenso_ies SET nome = 'FETAC FACULDADE DE EDUCACAO TECNOLOGIA E ADMINISTRACAO DE CAARAPO' WHERE ies_id = 12748;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADES UNIDAS DE PESQUISA CIENCIAS E SAUDE LTDA' WHERE ies_id = 12749;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE DE TECNOLOGIA FTEC' WHERE ies_id = 12784;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE INSTITUTO BRASIL DE ENSINO IBRA' WHERE ies_id = 12899;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE CGESP GOIANIA' WHERE ies_id = 12928;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE PITAGORAS DE GOIANIA' WHERE ies_id = 13133;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE IDEAU DE BAGE' WHERE ies_id = 13359;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE DE CIENCIAS EDUCACAO SAUDE PESQUISA E GESTAO' WHERE ies_id = 13631;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE DE SAO MARCOS' WHERE ies_id = 13648;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE UNIATENEU' WHERE ies_id = 13657;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE IBCMED' WHERE ies_id = 13696;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADES DO VALE DO ARARANGUA FVA' WHERE ies_id = 13717;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE DE TECNOLOGIA CAPACITACAO E GESTAO INTEGRAL' WHERE ies_id = 13735;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE ESTACIO DE FEIRA DE SANTANA' WHERE ies_id = 13783;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE SISTEMA DE ENSINO GAUCHO' WHERE ies_id = 13865;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE UNINASSAU BELEM' WHERE ies_id = 13982;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE DOS GUARARAPES' WHERE ies_id = 14002;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSITARIO UNA DE BETIM' WHERE ies_id = 14028;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE UNICA DE CONTAGEM' WHERE ies_id = 14161;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE UNICA DE TIMOTEO' WHERE ies_id = 14242;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE UNIRB PARNAIBA' WHERE ies_id = 14297;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSITARIO MAURICIO DE NASSAU DE FORTALEZA' WHERE ies_id = 14321;
            UPDATE modules.educacenso_ies SET nome = 'INSTITUTO FEDERAL DE EDUCACAO CIENCIA E TECNOLOGIA DE BRASILIA' WHERE ies_id = 14408;
            UPDATE modules.educacenso_ies SET nome = 'INSTITUTO FEDERAL DE EDUCACAO CIENCIA E TECNOLOGIA BAIANO' WHERE ies_id = 14509;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE UNINASSAU CARUARU' WHERE ies_id = 14717;
            UPDATE modules.educacenso_ies SET nome = 'INSTITUTO FEDERAL DE EDUCACAO CIENCIA E TECNOLOGIA DO PARANA' WHERE ies_id = 14724;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE FAIPE' WHERE ies_id = 14869;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE DE CIENCIAS DA SAUDE DE BARRETOS DR PAULO PRATA' WHERE ies_id = 14892;
            UPDATE modules.educacenso_ies SET nome = 'UNIVERSIDADE FEDERAL DA INTEGRACAO LATINOAMERICANA' WHERE ies_id = 15001;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE EVANGELICA DE JARAGUA' WHERE ies_id = 15173;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE DE TECNOLOGIA EDUCACAO SUPERIOR E PROFISSIONAL' WHERE ies_id = 15272;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE BRASILEIRA DE ENSINO PESQUISA E EXTENSAO' WHERE ies_id = 15280;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO DE ENSINO SUPERIOR RIOGRANDENSE MARAU CESURG' WHERE ies_id = 15351;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE UNIRB NATAL' WHERE ies_id = 15428;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE CATOLICA DE MATO GROSSO' WHERE ies_id = 15433;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE DA INDUSTRIA CURITIBA' WHERE ies_id = 15445;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE UNICA DE IPATINGA' WHERE ies_id = 15450;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSITARIO UNA DE BOM DESPACHO' WHERE ies_id = 15452;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE DE TECNOLOGIA SENAI SUICOBRASILEIRA PAULO ERNESTO TOLLE' WHERE ies_id = 15502;
            UPDATE modules.educacenso_ies SET nome = 'INSTITUTO FEDERAL DE EDUCACAO CIENCIA E TECNOLOGIA DO ACRE' WHERE ies_id = 15507;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO DE ENSINO UNIFICADO DO PIAUI' WHERE ies_id = 15508;
            UPDATE modules.educacenso_ies SET nome = 'INSTITUTO FEDERAL DE EDUCACAO CIENCIA E TECNOLOGIA DE MATO GROSSO DO SUL' WHERE ies_id = 15520;
            UPDATE modules.educacenso_ies SET nome = 'INSTITUTO FEDERAL DE EDUCACAO CIENCIA E TECNOLOGIA DO AMAPA' WHERE ies_id = 15522;
            UPDATE modules.educacenso_ies SET nome = 'FATEC CRUZEIRO PROF WALDOMIRO MAY' WHERE ies_id = 15680;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE DE TECNOLOGIA DE ITAPETININGA PROF ANTONIO BELIZANDRO BARBOSA REZENDE' WHERE ies_id = 15693;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE DE TECNOLOGIA DR THOMAZ NOVELINO' WHERE ies_id = 15708;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE DE TECNOLOGIA PROFESSOR ANTONIO SEABRA' WHERE ies_id = 15715;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE DE TECNOLOGIA NILO DE STEFANI JABOTICABAL' WHERE ies_id = 15753;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE DE TECNOLOGIA DE TATUI PROF WILSON ROBERTO RIBEIRO DE CAMARGO' WHERE ies_id = 15803;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE PITAGORAS DA PARAIBA' WHERE ies_id = 15839;
            UPDATE modules.educacenso_ies SET nome = 'SOBRESP FACULDADE DE CIENCIAS DA SAUDE' WHERE ies_id = 15894;
            UPDATE modules.educacenso_ies SET nome = 'FG FACULDADE GLOBAL' WHERE ies_id = 15980;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE UNIRB CEARA' WHERE ies_id = 16453;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE DE CIENCIAS HUMANAS ECONOMICAS E DA SAUDE' WHERE ies_id = 16728;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE DO BICO' WHERE ies_id = 16759;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE INTERNACIONAL DE SAO LUIS' WHERE ies_id = 16894;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE MELIES DE TECNOLOGIA' WHERE ies_id = 16934;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE UNINASSAU PARNAMIRIM' WHERE ies_id = 16943;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE SENAI RIO' WHERE ies_id = 16967;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE CERS' WHERE ies_id = 17091;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE TRES MARIAS' WHERE ies_id = 17115;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE SENAC CRICIUMA' WHERE ies_id = 17277;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE UNINASSAU SAO LUIS' WHERE ies_id = 17284;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE URIEL DE ALMEIDA LEITAO' WHERE ies_id = 17289;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE ALIS DE ITABIRITO' WHERE ies_id = 17348;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE DE TECNOLOGIA COESP' WHERE ies_id = 17563;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE DE CIENCIAS HUMANAS EXATAS E DA SAUDE DO PIAUI' WHERE ies_id = 17565;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE PROF WLADEMIR DOS SANTOS' WHERE ies_id = 17598;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE UNINASSAU FORTALEZA SAVANAH' WHERE ies_id = 17622;
            UPDATE modules.educacenso_ies SET nome = 'ESCOLA DE DIREITO DO BRASIL' WHERE ies_id = 17672;
            UPDATE modules.educacenso_ies SET nome = 'FAPFACULDADE DE PINHEIROS' WHERE ies_id = 17701;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE SESISP DE EDUCACAO' WHERE ies_id = 17731;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE SENAI DA PARAIBA' WHERE ies_id = 17763;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE UNINASSAU FEIRA DE SANTANA' WHERE ies_id = 17816;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE DO CENTRO LESTE CARIACICA' WHERE ies_id = 17828;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE UNINASSAU PETROLINA' WHERE ies_id = 18023;
            UPDATE modules.educacenso_ies SET nome = 'CISNE FACULDADE DE QUIXADA' WHERE ies_id = 18065;
            UPDATE modules.educacenso_ies SET nome = 'CISNE FACULDADE TECNOLOGICA DE QUIXADA' WHERE ies_id = 18067;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE UNINASSAU JABOATAO DOS GUARARAPES' WHERE ies_id = 18075;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE UNIDA DE CAMPINAS GOIANIA FACUNICAMPS GOIANIA' WHERE ies_id = 18133;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE HORUS SAO MIGUEL' WHERE ies_id = 18257;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE LATINOAMERICANA' WHERE ies_id = 18288;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE UNIFAMETRO MARACANAU' WHERE ies_id = 19337;
            UPDATE modules.educacenso_ies SET nome = 'CENTRO UNIVERSITARIO IMEPAC ARAGUARI' WHERE ies_id = 19512;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE DE TECNOLOGIA JORGE CARAM SABBAG' WHERE ies_id = 19862;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE DE EDUCACAO E CULTURA DE JIPARANA' WHERE ies_id = 11748;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE SANTA TERESA' WHERE ies_id = 18684;
            UPDATE modules.educacenso_ies SET nome = 'UNAMA FACULDADE DA AMAZONIA DE BOA VISTA' WHERE ies_id = 18651;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE PITAGORAS UNIDADE PARAGOMINAS' WHERE ies_id = 17666;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE PITAGORAS UNIDADE PARAUAPEBAS' WHERE ies_id = 17667;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE DE ENSINO SUPERIOR DO SUL DO PARA' WHERE ies_id = 16816;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE UNIRB FORTALEZA' WHERE ies_id = 19206;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADES INTEGRADAS DO CEARA UNIFIC' WHERE ies_id = 19173;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE VIDAL' WHERE ies_id = 17499;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE FADAM' WHERE ies_id = 17688;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE VIA SAPIENS' WHERE ies_id = 19597;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE UNINABUCO JOAO PESSOA' WHERE ies_id = 19329;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE UNINASSAU CABO' WHERE ies_id = 18211;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE UNINASSAU OLINDA' WHERE ies_id = 18210;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE CESAR' WHERE ies_id = 19327;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE AUTONOMA DO BRASIL MACEIO' WHERE ies_id = 20494;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE AGES DE TUCANO' WHERE ies_id = 18296;
            UPDATE modules.educacenso_ies SET nome = 'ALFA FACULDADE DE ARACUAI' WHERE ies_id = 18520;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE ESTACIO DE BARBACENA ESTACIOBARBACENA' WHERE ies_id = 18132;
            UPDATE modules.educacenso_ies SET nome = 'ALFA FACULDADE DE GUANHAES' WHERE ies_id = 18692;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE FELUMA SAUDE TECNOLOGIA E CIENCIA' WHERE ies_id = 14738;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE CNEC DE EDUCACAO DE UBERABA' WHERE ies_id = 14383;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE TELOS' WHERE ies_id = 18036;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE ESTACIO DE SAO MATEUS ESTACIO SAO MATEUS' WHERE ies_id = 18107;
            UPDATE modules.educacenso_ies SET nome = 'ESCOLA DE COMANDO E ESTADOMAIOR DO EXERCITO' WHERE ies_id = 21436;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE SAO LUCAS DE CACAPAVA' WHERE ies_id = 18667;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE FEBRACIS' WHERE ies_id = 18696;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE DOM RICARDO' WHERE ies_id = 13752;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE DE AGRONEGOCIOS DE HOLAMBRA' WHERE ies_id = 20465;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE UNIFICADA DO ESTADO DE SAO PAULO' WHERE ies_id = 18258;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE DE OSASCO' WHERE ies_id = 18526;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE DE EDUCACAO E TECNOLOGIA DE SAO CARLOS' WHERE ies_id = 17899;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE ESTACIO DE RIO PRETO' WHERE ies_id = 17803;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE HUMBOLDT' WHERE ies_id = 17587;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE CEAT' WHERE ies_id = 18072;
            UPDATE modules.educacenso_ies SET nome = 'INSTITUTO DE ENSINO E PESQUISA DO HOSPITAL SIRIOLIBANES' WHERE ies_id = 21509;
            UPDATE modules.educacenso_ies SET nome = 'FIP FACULDADE DE IPORA PARANA' WHERE ies_id = 19189;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE SENAC CONCORDIA' WHERE ies_id = 17777;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE SENAC PALHOCA' WHERE ies_id = 18201;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADES JOAO PAULO II PELOTAS' WHERE ies_id = 19587;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADES JOAO PAULO II CAMPUS PORTO ALEGRE' WHERE ies_id = 19542;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE DE ADMINISTRACAO HUMANAS E EXATAS' WHERE ies_id = 18463;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE AGORA FAG' WHERE ies_id = 18616;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE DE TECNOLOGIA AVANCADA' WHERE ies_id = 20455;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE UNA DE CATALAO' WHERE ies_id = 18474;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE SOLIDARIA DE SOBRADINHO' WHERE ies_id = 18509;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE UNIRB SALVADOR' WHERE ies_id = 16459;
            UPDATE modules.educacenso_ies SET nome = 'ACADEMIA NACIONAL DE POLICIA ANP' WHERE ies_id = 17613;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE BSSP' WHERE ies_id = 18009;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE ESTACIO DE IMPERATRIZ ESTACIO IMPERATRIZ' WHERE ies_id = 18260;
            UPDATE modules.educacenso_ies SET nome = 'FAINIC FACULDADES INTEGRADAS NIC' WHERE ies_id = 18319;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE UNINASSAU ANANINDEUA' WHERE ies_id = 18642;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE UNINASSAU MOSSORO' WHERE ies_id = 18649;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE UNINASSAU GARANHUNS' WHERE ies_id = 18653;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE PITAGORAS DO CEARA' WHERE ies_id = 18659;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE UNIVERITAS UNIVERSUS VERITAS DE GOIANIA' WHERE ies_id = 18673;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE UNINASSAU PALMAS' WHERE ies_id = 18676;
            UPDATE modules.educacenso_ies SET nome = 'INSTITUTO RACINE DE EDUCACAO SUPERIOR' WHERE ies_id = 18698;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE DE TEOLOGIA FORTALEZA FATEFOR' WHERE ies_id = 19171;
            UPDATE modules.educacenso_ies SET nome = 'ESCOLA DE POLITICAS PUBLICAS E GOVERNO' WHERE ies_id = 19320;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE UNINABUCO BELEM' WHERE ies_id = 19332;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE UNINASSAU FORTALEZA PARANGABA' WHERE ies_id = 19333;
            UPDATE modules.educacenso_ies SET nome = 'FACIULDADE UNINASSAU BRASILIA' WHERE ies_id = 19334;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE UNINABUCO MANAUS' WHERE ies_id = 19342;
            UPDATE modules.educacenso_ies SET nome = 'EMGE ESCOLA DE ENGENHARIA' WHERE ies_id = 19476;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE UNINASSAU SOBRAL' WHERE ies_id = 19844;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE AUTONOMA DO BRASIL CABO DE SANTO AGOSTINHO' WHERE ies_id = 19846;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE UNIVERITAS UNIVERSUS VERITAS DE VITORIA' WHERE ies_id = 19849;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE UNIFAMETRO CASCAVEL' WHERE ies_id = 19859;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE SAPIENS' WHERE ies_id = 19943;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE CAPITAL FEDERAL DE ITAPECERICA DA SERRA' WHERE ies_id = 19966;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE DOMUS SAPIENS' WHERE ies_id = 20122;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE PADRE CICERO' WHERE ies_id = 20200;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE DO INSTITUTO SUPERIOR DE EDUCACAO ISE' WHERE ies_id = 20541;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE UNINTA ITAPIPOCA' WHERE ies_id = 20547;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE SULAMERICA BRASILIA' WHERE ies_id = 20561;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADES SULAMERICA BAHIA' WHERE ies_id = 20605;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE DE TECNOLOGIA E CIENCIAS FTC PETROLINA' WHERE ies_id = 20607;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE UNIRB TERESINA' WHERE ies_id = 20643;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE UNIRB PIAUI' WHERE ies_id = 21240;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE UNIVERITAS UNIVERSUS VERITAS DE PORTO ALEGRE' WHERE ies_id = 21364;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE UNIVERITAS UNIVERSUS VERITAS DE CURITIBA' WHERE ies_id = 21366;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE UNINASSAU CUIABA' WHERE ies_id = 21411;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE UNINABUCO SALVADOR' WHERE ies_id = 21421;
            UPDATE modules.educacenso_ies SET nome = 'INSTITUTO SUPERIOR DA CONVENCAO NAC DAS ASSEMBLEIAS DE DEUS' WHERE ies_id = 21446;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE PLUS' WHERE ies_id = 21593;
            UPDATE modules.educacenso_ies SET nome = 'FACULDADE DE TECNOLOGIA FATEC DE RIBEIRAO PRETO' WHERE ies_id = 21713;
        ");
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        //
    }
}
