<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

class UpdateNomeInstituicaoEducacensoEis extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        DB::statement("
            UPDATE modules.educacenso_ies
                SET nome = (
                    CASE ies_id
                        WHEN 131 THEN 'FACULDADES INTEGRADAS DO ESTADO DE SAO PAULO'
                        WHEN 139 THEN 'FACULDADE UNIBRASILIA DE CIENCIAS ECONOMICAS DE MINAS GERAIS'
                        WHEN 242 THEN 'CENTRO UNIVERSITARIO ANHANGUERA PITAGORAS AMPL'
                        WHEN 337 THEN 'CENTRO UNIVERSITARIO ACADEMI'
                        WHEN 530 THEN 'FACULDADE DE MUSICA DO ESPIRITO SANTO MAURICIO DE OLIVEIRA'
                        WHEN 535 THEN 'FUNDACAO FACULDADE DE FILOSOFIA, CIENCIAS E LETRAS DE MANDAGUAR'
                        WHEN 640 THEN 'FACULDADE MARIA THEREZ'
                        WHEN 721 THEN 'FACULDADE DE ASSI'
                        WHEN 763 THEN 'CENTRO UNIVERSITARIO DE GOIANI'
                        WHEN 778 THEN 'FACULDADE IBRA DOS VALE'
                        WHEN 852 THEN 'FIAP  CENTRO UNIVERSITARI'
                        WHEN 1080 THEN 'CENTRO UNIVERSITARIO ARTHUR SA EARP NET'
                        WHEN 1196 THEN 'UNIVERSIDADE CESUMA'
                        WHEN 1237 THEN 'CENTRO UNIVERSITARIO NOSSA SENHORA APARECID'
                        WHEN 1244 THEN 'FACULDADE BRASILEIRA MULTIVIX VITORI'
                        WHEN 1326 THEN 'FACULDADE MULTIVIX SERR'
                        WHEN 1359 THEN 'FACULDADE MULTIVIX NOVA VENECI'
                        WHEN 1379 THEN 'CENTRO UNIVERSITARIO FAES'
                        WHEN 1383 THEN 'FACULDADE NOVO HORIZONTE DE IPOJUC'
                        WHEN 1403 THEN 'FACULDADE ESTACIO DE PIMENTA BUEN'
                        WHEN 1494 THEN 'CENTRO UNIVERSITARIO SALESIAN'
                        WHEN 1523 THEN 'CENTRO DE ENSINO SUPERIOR CESU'
                        WHEN 1573 THEN 'CENTRO UNIVERSITARIO ALFREDO NASSE'
                        WHEN 1636 THEN 'FACULDADE MONTE PASCOA'
                        WHEN 1663 THEN 'CENTRO UNIVERSITARIO ARAGUAI'
                        WHEN 1703 THEN 'FACULDADE UNIBRAS DE GOIA'
                        WHEN 1723 THEN 'STRONG BUSINESS SCHOO'
                        WHEN 1734 THEN 'CENTRO UNIVERSITARIO FACID WYDE'
                        WHEN 1739 THEN 'FACULDADE UNIBRASILIA SU'
                        WHEN 1864 THEN 'FACULDADE DA ASSOCIACAO BRASILIENSE DE EDUCACA'
                        WHEN 1872 THEN 'CENTRO UNIVERSITARIO SANTA CRUZ DE CURITIB'
                        WHEN 1894 THEN 'FACULDADE EUROPEIA DE TECNOLOGIA E CIENCIAS HUMANAS  EUROTEC'
                        WHEN 1917 THEN 'CENTRO UNIVERSITARIO UNIFACIME'
                        WHEN 1936 THEN 'CENTRO UNIVERSITARIO LA SALL'
                        WHEN 1956 THEN 'FACULDADE UNIRB  ALAGOA'
                        WHEN 1965 THEN 'CENTRO UNIVERSITARIO MARIO PONTES JUC'
                        WHEN 1970 THEN 'FACULDADE MULTIVIX DE CACHOEIR'
                        WHEN 2035 THEN 'FACULDADE FATIFAJAR JAGUARIAIV'
                        WHEN 2133 THEN 'FACULDADE DE CIENCIAS, EDUCACAO E TEOLOGIA DO NORTE DO BRASIL'
                        WHEN 2229 THEN 'FACULDADE UNIS SAO LOURENC'
                        WHEN 2266 THEN 'FACULDADE UNIAO DE GOYAZES FORMOS'
                        WHEN 2336 THEN 'CENTRO UNIVERSITARIO BRASILIA DO ESTADO DE GOIAS'
                        WHEN 2426 THEN 'CENTRO UNIVERSITARIO FIBR'
                        WHEN 2537 THEN 'FACULDADE MULTIVIX CARIACIC'
                        WHEN 2593 THEN 'CENTRO UNIVERSITARIO DE JUAZEIRO DO NORT'
                        WHEN 2613 THEN 'CENTRO UNIVERSITARIO ESTACIO META DE RIO BRANCO ESTACIO UNIMET'
                        WHEN 2625 THEN 'FACULDADE APRIMORAR DE SAO JOSE DOS CAMPO'
                        WHEN 2754 THEN 'FACULDADE ESTACIO SAO PAULO DE RONDONI'
                        WHEN 2827 THEN 'FACULDADE DE EDUCACAO DO PIAU'
                        WHEN 2896 THEN 'CENTRO UNIVERSITARIO SAT'
                        WHEN 2961 THEN 'FACULDADE ESTACIO DO PANTANA'
                        WHEN 2973 THEN 'FACULDADES INTEGRADAS DE PRIMAVERA DO LEST'
                        WHEN 3204 THEN 'FACULDADE UNIBRAS DO MATO GROSS'
                        WHEN 3205 THEN 'CENTRO UNIVERSITARIO DE VICOS'
                        WHEN 3339 THEN 'CENTRO UNIVERSITARIO IDEA'
                        WHEN 3365 THEN 'FACULDADE UNIBRAS DA BAHI'
                        WHEN 3388 THEN 'CENTRO UNIVERSITARIO PARAIS'
                        WHEN 3443 THEN 'CENTRO UNIVERSITARIO CESUC'
                        WHEN 3657 THEN 'FACULDADE UNICA DE MONTES CLARO'
                        WHEN 3746 THEN 'FACULDADE GRANDE SAO PAULO'
                        WHEN 3797 THEN 'CENTRO UNIVERSITARIO GUAIRAC'
                        WHEN 3854 THEN 'FACULDADE IBRA DE BRASILIA'
                        WHEN 3980 THEN 'FACULDADE JK CC'
                        WHEN 4045 THEN 'CENTRO UNIVERSITARIO UNICURITIB'
                        WHEN 4095 THEN 'FACULDADE DE TECNOLOGIA E CIENCIAS DO DISTRITO FEDERA'
                        WHEN 4096 THEN 'FACULDADE DE TECNOLOGIA FTEC DE PORTO ALEGR'
                        WHEN 4097 THEN 'FACULDADE DE TECNOLOGIA FTEC DE BENTO GONCALVE'
                        WHEN 4118 THEN 'CENTRO UNIVERSITARIO MAURICIO DE NASSAU PAULIST'
                        WHEN 4135 THEN 'FACULDADE UNINORT'
                        WHEN 4166 THEN 'FACULDADE UNIBRASILIA DE MINAS GERAI'
                        WHEN 4261 THEN 'FACULDADE CM'
                        WHEN 4411 THEN 'FACULDADE ESTACIO UNIJIPA DE JIPARAN'
                        WHEN 4420 THEN 'CENTRO UNIVERSITARIO AESO   BARROS MEL'
                        WHEN 4584 THEN 'FACULDADE ESP'
                        WHEN 4586 THEN 'FACULDADE UNIBRAS DO NORTE GOIAN'
                        WHEN 4751 THEN 'CENTRO UNIVERSITARIO UNIFATECI'
                        WHEN 4766 THEN 'CENTRO UNIVERSITARIO UNA DE CONTAGE'
                        WHEN 4873 THEN 'FACULDADE IBRA DE TAUBAT'
                        WHEN 4889 THEN 'FACULDADE CONECTADA FACONNEC'
                        WHEN 4943 THEN 'STRONG BUSINESS SCHOOL B'
                        WHEN 4983 THEN 'FACULDADE IBRA DE TECNOLOGIA'
                        WHEN 5008 THEN 'FACULDADES FAME'
                        WHEN 5025 THEN 'FACULDADE UNIN'
                        WHEN 5387 THEN 'FACULDADE IMPACT'
                        WHEN 5592 THEN 'CENTRO UNIVERSITARIO FUNORT'
                        WHEN 10251 THEN 'FACULDADE METODISTA CONEXIONA'
                        WHEN 10685 THEN 'FACULDADE MULTIVIX SAO MATEU'
                        WHEN 11593 THEN 'FACULDADE CRISTA DA AMAZONI'
                        WHEN 11807 THEN 'ISTITUTO EUROPEO DI DESIG'
                        WHEN 11895 THEN 'FACULDADE UNIBRASILI'
                        WHEN 15351 THEN 'FACULDADE CESURG MARA'
                        WHEN 16728 THEN 'INSTITUTO TOCANTINENSE PRESIDENTE ANTONIO CARLO'
                        WHEN 16934 THEN 'FACULDADE MELIE'
                        WHEN 17291 THEN 'FACULDADE ESE'
                        WHEN 17322 THEN 'FACULDADE ABERTA DO TOCANTIN'
                        WHEN 18036 THEN 'FACULDADE DE EMPREENDEDORISMO E CIENCIAS HUMANA'
                        WHEN 18319 THEN 'FACULDADES INTEGRADAS VITAL BRAZI'
                        WHEN 18652 THEN 'FACULDADE UNIJUAZEIR'
                        WHEN 18667 THEN 'FACULDADE SANTO ANTONI'
                        WHEN 18679 THEN 'FACULDADE DE ADMINISTRACAO, COMERCIO E EMPREENDEDORISM'
                        WHEN 18696 THEN 'FACULDADE DYNAMUS DE CAMPINAS'
                        WHEN 18711 THEN 'FACULDADE INOVA MAIS DE SAO PAUL'
                        WHEN 18979 THEN 'FACULDADE MULTIVIX VILA VELH'
                        WHEN 19216 THEN 'FACULDADE GOYAZES DO DISTRITO FEDERA'
                        WHEN 19284 THEN 'FACULDADE BRASILEIRA DO RECONCAV'
                        WHEN 19369 THEN 'FACULDADE CEA'
                        WHEN 19956 THEN 'FACULDADE UNIRB JOAO PESSO'
                        WHEN 19957 THEN 'FACULDADE UNIRB PARNAMIRI'
                        WHEN 19963 THEN 'FACULDADE DE CIENCIAS ODONTOLOGICA'
                        WHEN 20591 THEN 'FACULDADE UNIS POUSO ALEGR'
                        WHEN 21638 THEN 'FACULDADE PECEG'
                        WHEN 21819 THEN 'FACULDADE REGIONAL DO AMAZONA'
                        WHEN 21950 THEN 'FACULDADE TUCURUI'
                        WHEN 22158 THEN 'FACULDADE UNOPAR DE CIENCIAS JURIDICAS DE PETROLIN'
                        WHEN 22168 THEN 'FACULDADE UNOPAR DE CIENCIAS JURIDICAS DE SANTA CRUZ DO SU'
                        WHEN 22236 THEN 'FACULDADE UNOPAR DE CIENCIAS JURIDICAS DE SETE LAGOA'
                        WHEN 22325 THEN 'FACULDADE CHRISTU'
                        WHEN 22326 THEN 'FACULDADE BRASILIA'
                    END
                )
            WHERE ies_id IN (
                131,139,242,337,530,535,640,721,763,778,852,1080,1196,1237,1244,1326,1359,1379,1383,1403,
                1494,1523,1573,1636,1663,1703,1723,1734,1739,1864,1872,1894,1917,1936,1956,1965,1970,2035,
                2133,2229,2266,2336,2426,2537,2593,2613,2625,2754,2827,2896,2961,2973,3204,3205,3339,3365,
                3388,3443,3657,3746,3797,3854,3980,4045,4095,4096,4097,4118,4135,4166,4261,4411,4420,4584,
                4586,4751,4766,4873,4889,4943,4983,5008,5025,5387,5592,10251,10685,11593,11807,11895,15351,
                16728,16934,17291,17322,18036,18319,18652,18667,18679,18696,18711,18979,19216,19284,19369,
                19956,19957,19963,20591,21638,21819,21950,22158,22168,22236,22325,22326
            )
        ");
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        //
    }
}
