<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

class UpdateNomeInstituicaoEducacensoEis extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        DB::statement('
            UPDATE modules.educacenso_ies
                SET nome = (
                    CASE ies_id
                        WHEN 131 THEN \'FACULDADES INTEGRADAS DO ESTADO DE SAO PAULO\'
                        WHEN 139 THEN \'FACULDADE UNIBRASILIA DE CIENCIAS ECONOMICAS DE MINAS GERAIS\'
                        WHEN 242 THEN \'CENTRO UNIVERSITARIO ANHANGUERA PITAGORAS AMPLI\'
                        WHEN 337 THEN \'CENTRO UNIVERSITARIO ACADEMIA\'
                        WHEN 530 THEN \'FACULDADE DE MUSICA DO ESPIRITO SANTO MAURICIO DE OLIVEIRA\'
                        WHEN 535 THEN \'FUNDACAO FACULDADE DE FILOSOFIA, CIENCIAS E LETRAS DE MANDAGUARI\'
                        WHEN 640 THEN \'FACULDADE MARIA THEREZA\'
                        WHEN 721 THEN \'FACULDADE DE ASSIS\'
                        WHEN 763 THEN \'CENTRO UNIVERSITARIO DE GOIANIA\'
                        WHEN 778 THEN \'FACULDADE IBRA DOS VALES\'
                        WHEN 852 THEN \'FIAP  CENTRO UNIVERSITARIO\'
                        WHEN 1080 THEN \'CENTRO UNIVERSITARIO ARTHUR SA EARP NETO\'
                        WHEN 1196 THEN \'UNIVERSIDADE CESUMAR\'
                        WHEN 1237 THEN \'CENTRO UNIVERSITARIO NOSSA SENHORA APARECIDA\'
                        WHEN 1244 THEN \'FACULDADE BRASILEIRA MULTIVIX VITORIA\'
                        WHEN 1326 THEN \'FACULDADE MULTIVIX SERRA\'
                        WHEN 1359 THEN \'FACULDADE MULTIVIX NOVA VENECIA\'
                        WHEN 1379 THEN \'CENTRO UNIVERSITARIO FAESA\'
                        WHEN 1383 THEN \'FACULDADE NOVO HORIZONTE DE IPOJUCA\'
                        WHEN 1403 THEN \'FACULDADE ESTACIO DE PIMENTA BUENO\'
                        WHEN 1494 THEN \'CENTRO UNIVERSITARIO SALESIANO\'
                        WHEN 1523 THEN \'CENTRO DE ENSINO SUPERIOR CESUL\'
                        WHEN 1573 THEN \'CENTRO UNIVERSITARIO ALFREDO NASSER\'
                        WHEN 1636 THEN \'FACULDADE MONTE PASCOAL\'
                        WHEN 1663 THEN \'CENTRO UNIVERSITARIO ARAGUAIA\'
                        WHEN 1703 THEN \'FACULDADE UNIBRAS DE GOIAS\'
                        WHEN 1723 THEN \'STRONG BUSINESS SCHOOL\'
                        WHEN 1734 THEN \'CENTRO UNIVERSITARIO FACID WYDEN\'
                        WHEN 1739 THEN \'FACULDADE UNIBRASILIA SUL\'
                        WHEN 1864 THEN \'FACULDADE DA ASSOCIACAO BRASILIENSE DE EDUCACAO\'
                        WHEN 1872 THEN \'CENTRO UNIVERSITARIO SANTA CRUZ DE CURITIBA\'
                        WHEN 1894 THEN \'FACULDADE EUROPEIA DE TECNOLOGIA E CIENCIAS HUMANAS  EUROTECH\'
                        WHEN 1917 THEN \'CENTRO UNIVERSITARIO UNIFACIMED\'
                        WHEN 1936 THEN \'CENTRO UNIVERSITARIO LA SALLE\'
                        WHEN 1956 THEN \'FACULDADE UNIRB  ALAGOAS\'
                        WHEN 1965 THEN \'CENTRO UNIVERSITARIO MARIO PONTES JUCA\'
                        WHEN 1970 THEN \'FACULDADE MULTIVIX DE CACHOEIRO\'
                        WHEN 2035 THEN \'FACULDADE FATIFAJAR JAGUARIAIVA\'
                        WHEN 2133 THEN \'FACULDADE DE CIENCIAS, EDUCACAO E TEOLOGIA DO NORTE DO BRASIL\'
                        WHEN 2229 THEN \'FACULDADE UNIS SAO LOURENCO\'
                        WHEN 2266 THEN \'FACULDADE UNIAO DE GOYAZES FORMOSA\'
                        WHEN 2336 THEN \'CENTRO UNIVERSITARIO BRASILIA DO ESTADO DE GOIAS\'
                        WHEN 2426 THEN \'CENTRO UNIVERSITARIO FIBRA\'
                        WHEN 2537 THEN \'FACULDADE MULTIVIX CARIACICA\'
                        WHEN 2593 THEN \'CENTRO UNIVERSITARIO DE JUAZEIRO DO NORTE\'
                        WHEN 2613 THEN \'CENTRO UNIVERSITARIO ESTACIO META DE RIO BRANCO ESTACIO UNIMETA\'
                        WHEN 2625 THEN \'FACULDADE APRIMORAR DE SAO JOSE DOS CAMPOS\'
                        WHEN 2754 THEN \'FACULDADE ESTACIO SAO PAULO DE RONDONIA\'
                        WHEN 2827 THEN \'FACULDADE DE EDUCACAO DO PIAUI\'
                        WHEN 2896 THEN \'CENTRO UNIVERSITARIO SATC\'
                        WHEN 2961 THEN \'FACULDADE ESTACIO DO PANTANAL\'
                        WHEN 2973 THEN \'FACULDADES INTEGRADAS DE PRIMAVERA DO LESTE\'
                        WHEN 3204 THEN \'FACULDADE UNIBRAS DO MATO GROSSO\'
                        WHEN 3205 THEN \'CENTRO UNIVERSITARIO DE VICOSA\'
                        WHEN 3339 THEN \'CENTRO UNIVERSITARIO IDEAU\'
                        WHEN 3365 THEN \'FACULDADE UNIBRAS DA BAHIA\'
                        WHEN 3388 THEN \'CENTRO UNIVERSITARIO PARAISO\'
                        WHEN 3443 THEN \'CENTRO UNIVERSITARIO CESUCA\'
                        WHEN 3657 THEN \'FACULDADE UNICA DE MONTES CLAROS\'
                        WHEN 3746 THEN \'FACULDADE GRANDE SAO PAULO\'
                        WHEN 3797 THEN \'CENTRO UNIVERSITARIO GUAIRACA\'
                        WHEN 3854 THEN \'FACULDADE IBRA DE BRASILIA\'
                        WHEN 3980 THEN \'FACULDADE JK CCI\'
                        WHEN 4045 THEN \'CENTRO UNIVERSITARIO UNICURITIBA\'
                        WHEN 4095 THEN \'FACULDADE DE TECNOLOGIA E CIENCIAS DO DISTRITO FEDERAL\'
                        WHEN 4096 THEN \'FACULDADE DE TECNOLOGIA FTEC DE PORTO ALEGRE\'
                        WHEN 4097 THEN \'FACULDADE DE TECNOLOGIA FTEC DE BENTO GONCALVES\'
                        WHEN 4118 THEN \'CENTRO UNIVERSITARIO MAURICIO DE NASSAU PAULISTA\'
                        WHEN 4135 THEN \'FACULDADE UNINORTE\'
                        WHEN 4166 THEN \'FACULDADE UNIBRASILIA DE MINAS GERAIS\'
                        WHEN 4261 THEN \'FACULDADE CMB\'
                        WHEN 4411 THEN \'FACULDADE ESTACIO UNIJIPA DE JIPARANA\'
                        WHEN 4420 THEN \'CENTRO UNIVERSITARIO AESO BARROS MELO\'
                        WHEN 4584 THEN \'FACULDADE ESPG\'
                        WHEN 4586 THEN \'FACULDADE UNIBRAS DO NORTE GOIANO\'
                        WHEN 4751 THEN \'CENTRO UNIVERSITARIO UNIFATECIE\'
                        WHEN 4766 THEN \'CENTRO UNIVERSITARIO UNA DE CONTAGEM\'
                        WHEN 4873 THEN \'FACULDADE IBRA DE TAUBATE\'
                        WHEN 4889 THEN \'FACULDADE CONECTADA FACONNECT\'
                        WHEN 4943 THEN \'STRONG BUSINESS SCHOOL BS\'
                        WHEN 4983 THEN \'FACULDADE IBRA DE TECNOLOGIA\'
                        WHEN 5008 THEN \'FACULDADES FAMEP\'
                        WHEN 5025 THEN \'FACULDADE UNINA\'
                        WHEN 5387 THEN \'FACULDADE IMPACTA\'
                        WHEN 5592 THEN \'CENTRO UNIVERSITARIO FUNORTE\'
                        WHEN 10251 THEN \'FACULDADE METODISTA CONEXIONAL\'
                        WHEN 10685 THEN \'FACULDADE MULTIVIX SAO MATEUS\'
                        WHEN 11593 THEN \'FACULDADE CRISTA DA AMAZONIA\'
                        WHEN 11807 THEN \'ISTITUTO EUROPEO DI DESIGN\'
                        WHEN 11895 THEN \'FACULDADE UNIBRASILIA\'
                        WHEN 15351 THEN \'FACULDADE CESURG MARAU\'
                        WHEN 16728 THEN \'INSTITUTO TOCANTINENSE PRESIDENTE ANTONIO CARLOS\'
                        WHEN 16934 THEN \'FACULDADE MELIES\'
                        WHEN 17291 THEN \'FACULDADE ESEA\'
                        WHEN 17322 THEN \'FACULDADE ABERTA DO TOCANTINS\'
                        WHEN 18036 THEN \'FACULDADE DE EMPREENDEDORISMO E CIENCIAS HUMANAS\'
                        WHEN 18319 THEN \'FACULDADES INTEGRADAS VITAL BRAZIL\'
                        WHEN 18652 THEN \'FACULDADE UNIJUAZEIRO\'
                        WHEN 18667 THEN \'FACULDADE SANTO ANTONIO\'
                        WHEN 18679 THEN \'FACULDADE DE ADMINISTRACAO, COMERCIO E EMPREENDEDORISMO\'
                        WHEN 18696 THEN \'FACULDADE DYNAMUS DE CAMPINAS\'
                        WHEN 18711 THEN \'FACULDADE INOVA MAIS DE SAO PAULO\'
                        WHEN 18979 THEN \'FACULDADE MULTIVIX VILA VELHA\'
                        WHEN 19216 THEN \'FACULDADE GOYAZES DO DISTRITO FEDERAL\'
                        WHEN 19284 THEN \'FACULDADE BRASILEIRA DO RECONCAVO\'
                        WHEN 19369 THEN \'FACULDADE CEAM\'
                        WHEN 19956 THEN \'FACULDADE UNIRB JOAO PESSOA\'
                        WHEN 19957 THEN \'FACULDADE UNIRB PARNAMIRIM\'
                        WHEN 19963 THEN \'FACULDADE DE CIENCIAS ODONTOLOGICAS\'
                        WHEN 20591 THEN \'FACULDADE UNIS POUSO ALEGRE\'
                        WHEN 21638 THEN \'FACULDADE PECEGE\'
                        WHEN 21819 THEN \'FACULDADE REGIONAL DO AMAZONAS\'
                        WHEN 21950 THEN \'FACULDADE TUCURUI\'
                        WHEN 22158 THEN \'FACULDADE UNOPAR DE CIENCIAS JURIDICAS DE PETROLINA\'
                        WHEN 22168 THEN \'FACULDADE UNOPAR DE CIENCIAS JURIDICAS DE SANTA CRUZ DO SUL\'
                        WHEN 22236 THEN \'FACULDADE UNOPAR DE CIENCIAS JURIDICAS DE SETE LAGOAS\'
                        WHEN 22325 THEN \'FACULDADE CHRISTUS\'
                        WHEN 22326 THEN \'FACULDADE BRASILIA\'
                    END
                )
            WHERE ies_id IN (
                131,139,242,337,530,535,640,721,763,778,852,1080,1196,1237,1244,1326,1359,1379,1383,1403,
                1494,1523,1573,1636,1663,1703,1723,1734,1739,1864,1872,1894,1917,1936,1956,1965,1970,2035,
                2133,2229,2266,2336,2426,2537,2593,2613,2625,2754,2827,2896,2961,2973,3204,3205,3339,3365,
                3388,3443,3657,3746,3797,3854,3980,4045,4095,4096,4097,4118,4135,4166,4261,4411,4420,4584,
                4586,4751,4766,4873,4889,4943,4983,5008,5025,5387,5592,10251,10685,11593,11807,11895,15351,
                16728,16934,17291,17322,18036,18319,18652,18667,18679,18696,18711,18979,19216,19284,19369,
                19956,19957,19963,20591,21638,21819,21950,22158,22168,22236,22325,22326
            )
        ');
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        //
    }
}
