#!/bin/bash

VERSION=`cat VERSION | tr -d '[:space:]'`
FILE_VERSION=`echo ${VERSION} | tr . -`
BUILD_FOLDER=ieducar-${FILE_VERSION}

mkdir -p ${BUILD_FOLDER}/
git checkout-index --prefix=${BUILD_FOLDER}/ -a -f
cd ${BUILD_FOLDER}
cp ieducar/configuration/ieducar.ini.example ieducar/configuration/ieducar.ini
sed -i.bak 's/APP_ENV=local/APP_ENV=production/g' .env.example && rm .env.example.bak
sed -i.bak 's/APP_DEBUG=true/APP_DEBUG=false/g' .env.example && rm .env.example.bak
composer install --no-dev --ignore-platform-reqs --optimize-autoloader
git clone https://github.com/portabilis/i-educar-reports-package.git ieducar/modules/Reports
rm -fR ieducar/modules/Reports/.git
cd ..
tar -zcvf ieducar-${FILE_VERSION}.tar.gz ${BUILD_FOLDER}
rm -fR ${BUILD_FOLDER}
echo
echo "Build realizado!"
exit 0
