#!/bin/bash

VERSION=$1

if [ "$VERSION" = "" ]; then
    echo
    echo "Defina a versão para gerar um build. Exemplo:"
    echo "./makebuild 2.10.0"
    exit 1
fi

FILE_VERSION=`echo $VERSION | tr . -`
BUILD_FOLDER=ieducar-v-${FILE_VERSION}

mkdir -p ${BUILD_FOLDER}/
sudo rm -R ${BUILD_FOLDER}/* 2> /dev/null
git checkout-index --prefix=${BUILD_FOLDER}/ -a -f
cd ${BUILD_FOLDER}
composer install --ignore-platform-reqs --optimize-autoloader
git clone git@github.com:portabilis/i-educar-reports-package.git ieducar/modules/Reports
sudo rm -R ieducar/modules/Reports/.git
cd ..
tar -zcvf ieducar-v-${FILE_VERSION}.tar.gz ${BUILD_FOLDER}
