#!/bin/bash

VERSION=`cat VERSION | tr -d '[:space:]'`
FILE_VERSION=`echo $VERSION | tr . -`
BUILD_FOLDER=ieducar-v-${FILE_VERSION}

mkdir -p ${BUILD_FOLDER}/
sudo rm -R ${BUILD_FOLDER}/* 2> /dev/null
git checkout-index --prefix=${BUILD_FOLDER}/ -a -f
cd ${BUILD_FOLDER}
cp ieducar/configuration/ieducar.ini.example ieducar/configuration/ieducar.ini
sed -i 's/APP_ENV=local/APP_ENV=production/g' .env.example
sed -i 's/APP_DEBUG=true/APP_DEBUG=false/g' .env.example
composer install --no-dev --ignore-platform-reqs --optimize-autoloader
git clone git@github.com:portabilis/i-educar-reports-package.git ieducar/modules/Reports
sudo rm -R ieducar/modules/Reports/.git
cd ..
tar -zcvf ieducar-v-${FILE_VERSION}.tar.gz ${BUILD_FOLDER}
sudo rm -R ${BUILD_FOLDER}
echo
echo "Build realizado"
exit 0
