<?php

namespace iEducar\Modules\Api;

class Error
{
    const MISSING_STAGE_DEFAULT_ERROR = 1000;
    const MISSING_STAGE_TEACHER_ERROR = 1001;
    const MISSING_STAGE_COORDINATOR_ERROR = 1002;
    const GRADE_GREATER_THAN_MAX_ALLOWED = 1003;
    const GRADE_LESSER_THAN_MIN_ALLOWED = 1004;
}